window.__ModuleLoader__.load({ id: "@negen/locale", factory: (require) => { var module = { exports: {} }; var exports = module.exports;
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  CHAR_TABLE_SIZE: () => CHAR_TABLE_SIZE,
  COMMON_NS: () => COMMON_NS,
  CONVERT_FALLBACK: () => CONVERT_FALLBACK,
  DOCUMENT_LANGUAGE: () => DOCUMENT_LANGUAGE,
  FALLBACK_LOCALE: () => FALLBACK_LOCALE,
  FONT_CSS: () => FONT_CSS,
  LOCALES: () => LOCALES,
  LOCALE_IDS: () => LOCALE_IDS,
  LocaleRuntime: () => LocaleRuntime,
  SETTINGS_NS: () => SETTINGS_NS,
  apply: () => apply,
  convertZhTw: () => convertZhTw,
  inject: () => inject,
  installFontFallback: () => installFontFallback,
  matchTag: () => matchTag,
  name: () => name
});
module.exports = __toCommonJS(index_exports);

// src/locale-settings.ts
var LOCALE_SETTINGS_NAMESPACE = "locale";
var LOCALE_PREFERENCE_FIELD = "preference";
var LOCALE_IDS = ["zh", "zh-TW", "ja", "ko", "en"];
function isShipped(id) {
  return LOCALE_IDS.some((shipped) => shipped === id);
}
var LOCALES = Object.freeze([
  { id: "zh", label: "简体中文" },
  { id: "zh-TW", label: "繁體中文" },
  { id: "ja", label: "日本語" },
  { id: "ko", label: "한국어" },
  { id: "en", label: "English" }
]);
var FALLBACK_LOCALE = "en";
var CONVERT_FALLBACK = { "zh-TW": "zh" };
var DOCUMENT_LANGUAGE = {
  "zh": "zh-CN",
  "zh-TW": "zh-TW",
  "ja": "ja",
  "ko": "ko",
  "en": "en"
};

// src/locales/zh.ts
var zh = {
  "ok": "确定",
  "cancel": "取消",
  "close": "关闭",
  "copy": "复制",
  "copied": "复制成功",
  "retry": "重试",
  "loading": "加载中…",
  "load.failed": "加载失败",
  "submit": "提交",
  "submitting": "正在提交…",
  "next": "下一步",
  "previous": "上一步",
  "skip": "跳过",
  "delete": "删除",
  "edit": "编辑",
  "save": "保存",
  "search": "搜索",
  "more": "更多",
  "collapse": "收起",
  "expand": "展开",
  "back": "返回",
  "unknown": "未知",
  "none": "无",
  "truncated": "已截断"
};

// src/locales/en.ts
var en = {
  "ok": "OK",
  "cancel": "Cancel",
  "close": "Close",
  "copy": "Copy",
  "copied": "Copied",
  "retry": "Retry",
  "loading": "Loading…",
  "load.failed": "Failed to load",
  "submit": "Submit",
  "submitting": "Submitting…",
  "next": "Next",
  "previous": "Previous",
  "skip": "Skip",
  "delete": "Delete",
  "edit": "Edit",
  "save": "Save",
  "search": "Search",
  "more": "More",
  "collapse": "Collapse",
  "expand": "Expand",
  "back": "Back",
  "unknown": "Unknown",
  "none": "None",
  "truncated": "Truncated"
};

// src/locales/zh-tw.ts
var zhTW = {
  "ok": "確定",
  "cancel": "取消",
  "close": "關閉",
  "copy": "複製",
  "copied": "複製成功",
  "retry": "重試",
  "loading": "載入中…",
  "load.failed": "載入失敗",
  "submit": "提交",
  "submitting": "正在提交…",
  "next": "下一步",
  "previous": "上一步",
  "skip": "略過",
  "delete": "刪除",
  "edit": "編輯",
  "save": "儲存",
  "search": "搜尋",
  "more": "更多",
  "collapse": "收合",
  "expand": "展開",
  "back": "返回",
  "unknown": "未知",
  "none": "無",
  "truncated": "已截斷"
};

// src/locales/ja.ts
var ja = {
  "ok": "OK",
  "cancel": "キャンセル",
  "close": "閉じる",
  "copy": "コピー",
  "copied": "コピーしました",
  "retry": "再試行",
  "loading": "読み込み中…",
  "load.failed": "読み込みに失敗しました",
  "submit": "送信",
  "submitting": "送信中…",
  "next": "次へ",
  "previous": "前へ",
  "skip": "スキップ",
  "delete": "削除",
  "edit": "編集",
  "save": "保存",
  "search": "検索",
  "more": "もっと見る",
  "collapse": "折りたたむ",
  "expand": "展開",
  "back": "戻る",
  "unknown": "不明",
  "none": "なし",
  "truncated": "切り詰められました"
};

// src/locales/ko.ts
var ko = {
  "ok": "확인",
  "cancel": "취소",
  "close": "닫기",
  "copy": "복사",
  "copied": "복사됨",
  "retry": "다시 시도",
  "loading": "불러오는 중…",
  "load.failed": "불러오지 못했습니다",
  "submit": "제출",
  "submitting": "제출 중…",
  "next": "다음",
  "previous": "이전",
  "skip": "건너뛰기",
  "delete": "삭제",
  "edit": "편집",
  "save": "저장",
  "search": "검색",
  "more": "더 보기",
  "collapse": "접기",
  "expand": "펼치기",
  "back": "뒤로",
  "unknown": "알 수 없음",
  "none": "없음",
  "truncated": "잘림"
};

// src/locales/settings.ts
var zh2 = {
  "language.title": "语言"
};
var zhTW2 = {
  "language.title": "語言"
};
var ja2 = {
  "language.title": "言語"
};
var ko2 = {
  "language.title": "언어"
};
var en2 = {
  "language.title": "Language"
};

// dict/zh-tw-chars.json
var zh_tw_chars_default = {
  万: "萬",
  与: "與",
  专: "專",
  业: "業",
  丛: "叢",
  东: "東",
  丝: "絲",
  丢: "丟",
  两: "兩",
  严: "嚴",
  丧: "喪",
  个: "個",
  临: "臨",
  为: "為",
  丽: "麗",
  么: "麼",
  义: "義",
  乐: "樂",
  习: "習",
  乡: "鄉",
  买: "買",
  乱: "亂",
  争: "爭",
  于: "於",
  亏: "虧",
  云: "雲",
  亚: "亞",
  产: "產",
  亩: "畝",
  亲: "親",
  亿: "億",
  仅: "僅",
  从: "從",
  仓: "倉",
  仪: "儀",
  们: "們",
  价: "價",
  众: "眾",
  优: "優",
  会: "會",
  伞: "傘",
  伟: "偉",
  传: "傳",
  伤: "傷",
  伪: "偽",
  体: "體",
  佣: "傭",
  侠: "俠",
  侦: "偵",
  侧: "側",
  侨: "僑",
  侩: "儈",
  俩: "倆",
  倾: "傾",
  偿: "償",
  儿: "兒",
  党: "黨",
  兰: "蘭",
  关: "關",
  兴: "興",
  兹: "茲",
  养: "養",
  兽: "獸",
  内: "內",
  冈: "岡",
  写: "寫",
  军: "軍",
  农: "農",
  冯: "馮",
  决: "決",
  冻: "凍",
  净: "淨",
  准: "準",
  减: "減",
  凤: "鳳",
  凭: "憑",
  凯: "凱",
  击: "擊",
  凿: "鑿",
  划: "劃",
  刘: "劉",
  则: "則",
  刚: "剛",
  创: "創",
  删: "刪",
  别: "別",
  剂: "劑",
  剑: "劍",
  剧: "劇",
  劝: "勸",
  务: "務",
  动: "動",
  励: "勵",
  劲: "勁",
  劳: "勞",
  势: "勢",
  勋: "勳",
  匀: "勻",
  区: "區",
  医: "醫",
  华: "華",
  协: "協",
  单: "單",
  卖: "賣",
  卢: "盧",
  卫: "衛",
  厂: "廠",
  厅: "廳",
  历: "歷",
  厉: "厲",
  压: "壓",
  厌: "厭",
  厦: "廈",
  县: "縣",
  参: "參",
  双: "雙",
  发: "發",
  变: "變",
  叶: "葉",
  号: "號",
  叹: "嘆",
  后: "後",
  吓: "嚇",
  吕: "呂",
  吗: "嗎",
  吨: "噸",
  听: "聽",
  启: "啟",
  呕: "嘔",
  员: "員",
  呜: "嗚",
  咏: "詠",
  咸: "鹹",
  响: "響",
  哑: "啞",
  唤: "喚",
  啸: "嘯",
  喷: "噴",
  嘘: "噓",
  嘱: "囑",
  团: "團",
  园: "園",
  围: "圍",
  国: "國",
  图: "圖",
  圆: "圓",
  圣: "聖",
  场: "場",
  坏: "壞",
  块: "塊",
  坚: "堅",
  坛: "壇",
  坞: "塢",
  坟: "墳",
  坠: "墜",
  垒: "壘",
  垦: "墾",
  垫: "墊",
  堕: "墮",
  墙: "牆",
  壮: "壯",
  声: "聲",
  壳: "殼",
  壶: "壺",
  处: "處",
  备: "備",
  头: "頭",
  夸: "誇",
  夹: "夾",
  夺: "奪",
  奋: "奮",
  奖: "獎",
  妆: "妝",
  妇: "婦",
  妈: "媽",
  娄: "婁",
  娇: "嬌",
  婶: "嬸",
  孙: "孫",
  学: "學",
  宁: "寧",
  实: "實",
  审: "審",
  宪: "憲",
  宽: "寬",
  宾: "賓",
  对: "對",
  寻: "尋",
  导: "導",
  寿: "壽",
  将: "將",
  尔: "爾",
  尘: "塵",
  尝: "嘗",
  尧: "堯",
  尸: "屍",
  尽: "盡",
  层: "層",
  属: "屬",
  屡: "屢",
  屿: "嶼",
  岁: "歲",
  岂: "豈",
  岗: "崗",
  岛: "島",
  岭: "嶺",
  岳: "嶽",
  峡: "峽",
  崭: "嶄",
  巩: "鞏",
  币: "幣",
  帅: "帥",
  师: "師",
  帐: "帳",
  帘: "簾",
  帜: "幟",
  带: "帶",
  帧: "幀",
  帮: "幫",
  广: "廣",
  庆: "慶",
  库: "庫",
  应: "應",
  庙: "廟",
  庞: "龐",
  废: "廢",
  开: "開",
  弃: "棄",
  张: "張",
  弥: "彌",
  弯: "彎",
  弹: "彈",
  归: "歸",
  当: "當",
  录: "錄",
  彦: "彥",
  彻: "徹",
  径: "徑",
  忆: "憶",
  忧: "憂",
  怀: "懷",
  态: "態",
  怜: "憐",
  总: "總",
  恋: "戀",
  恳: "懇",
  悬: "懸",
  悯: "憫",
  惊: "驚",
  惧: "懼",
  惨: "慘",
  惩: "懲",
  惯: "慣",
  愤: "憤",
  愿: "願",
  慑: "懾",
  戏: "戲",
  战: "戰",
  户: "戶",
  执: "執",
  扩: "擴",
  扫: "掃",
  扬: "揚",
  扰: "擾",
  抠: "摳",
  抡: "掄",
  抢: "搶",
  护: "護",
  担: "擔",
  拟: "擬",
  拢: "攏",
  拣: "揀",
  拥: "擁",
  拦: "攔",
  拧: "擰",
  择: "擇",
  挂: "掛",
  挚: "摯",
  挟: "挾",
  挡: "擋",
  挣: "掙",
  挤: "擠",
  挥: "揮",
  捞: "撈",
  损: "損",
  换: "換",
  据: "據",
  掷: "擲",
  搀: "攙",
  搁: "擱",
  携: "攜",
  摄: "攝",
  摇: "搖",
  摊: "攤",
  攒: "攢",
  敌: "敵",
  敛: "斂",
  数: "數",
  斋: "齋",
  斩: "斬",
  断: "斷",
  无: "無",
  旧: "舊",
  时: "時",
  昼: "晝",
  显: "顯",
  晒: "曬",
  晓: "曉",
  暂: "暫",
  术: "術",
  朴: "樸",
  机: "機",
  杀: "殺",
  杂: "雜",
  权: "權",
  条: "條",
  来: "來",
  杨: "楊",
  极: "極",
  构: "構",
  枢: "樞",
  枣: "棗",
  枪: "槍",
  柜: "櫃",
  标: "標",
  栋: "棟",
  栏: "欄",
  树: "樹",
  样: "樣",
  档: "檔",
  桥: "橋",
  桨: "槳",
  梦: "夢",
  检: "檢",
  椭: "橢",
  楼: "樓",
  欢: "歡",
  欧: "歐",
  歼: "殲",
  殴: "毆",
  毁: "毀",
  毕: "畢",
  毡: "氈",
  气: "氣",
  汇: "匯",
  汤: "湯",
  汹: "洶",
  沟: "溝",
  没: "沒",
  沧: "滄",
  沪: "滬",
  泪: "淚",
  泻: "瀉",
  泼: "潑",
  泽: "澤",
  洁: "潔",
  洒: "灑",
  洼: "窪",
  浅: "淺",
  浆: "漿",
  浊: "濁",
  济: "濟",
  浏: "瀏",
  浑: "渾",
  浓: "濃",
  涂: "塗",
  涛: "濤",
  涝: "澇",
  涤: "滌",
  润: "潤",
  涨: "漲",
  涩: "澀",
  渊: "淵",
  渍: "漬",
  渗: "滲",
  温: "溫",
  湿: "濕",
  溅: "濺",
  滚: "滾",
  满: "滿",
  滤: "濾",
  滥: "濫",
  潜: "潛",
  灭: "滅",
  灯: "燈",
  灾: "災",
  炉: "爐",
  点: "點",
  炼: "煉",
  烂: "爛",
  烛: "燭",
  烟: "煙",
  烧: "燒",
  烩: "燴",
  烫: "燙",
  热: "熱",
  爱: "愛",
  爷: "爺",
  牵: "牽",
  牺: "犧",
  状: "狀",
  犹: "猶",
  独: "獨",
  狭: "狹",
  狮: "獅",
  狱: "獄",
  猎: "獵",
  猪: "豬",
  猫: "貓",
  献: "獻",
  獭: "獺",
  环: "環",
  现: "現",
  琐: "瑣",
  琼: "瓊",
  电: "電",
  画: "畫",
  疗: "療",
  疮: "瘡",
  疯: "瘋",
  痈: "癰",
  痒: "癢",
  痪: "瘓",
  癣: "癬",
  盏: "盞",
  盐: "鹽",
  监: "監",
  盖: "蓋",
  盘: "盤",
  着: "著",
  睁: "睜",
  瞩: "矚",
  矾: "礬",
  矿: "礦",
  码: "碼",
  砚: "硯",
  础: "礎",
  硕: "碩",
  确: "確",
  碍: "礙",
  碱: "鹼",
  礼: "禮",
  离: "離",
  种: "種",
  积: "積",
  称: "稱",
  秽: "穢",
  稳: "穩",
  穷: "窮",
  窃: "竊",
  窍: "竅",
  窜: "竄",
  竖: "豎",
  竞: "競",
  笔: "筆",
  笺: "箋",
  筑: "築",
  筛: "篩",
  签: "簽",
  简: "簡",
  篱: "籬",
  类: "類",
  粤: "粵",
  粪: "糞",
  粮: "糧",
  紧: "緊",
  纠: "糾",
  红: "紅",
  纤: "纖",
  约: "約",
  级: "級",
  纪: "紀",
  纫: "紉",
  纯: "純",
  纱: "紗",
  纵: "縱",
  纷: "紛",
  纸: "紙",
  纺: "紡",
  纽: "紐",
  线: "線",
  练: "練",
  组: "組",
  绅: "紳",
  细: "細",
  织: "織",
  终: "終",
  绍: "紹",
  经: "經",
  绒: "絨",
  结: "結",
  给: "給",
  络: "絡",
  绝: "絕",
  统: "統",
  绣: "繡",
  继: "繼",
  绩: "績",
  绪: "緒",
  续: "續",
  绳: "繩",
  维: "維",
  绵: "綿",
  综: "綜",
  绽: "綻",
  缀: "綴",
  缅: "緬",
  缓: "緩",
  缕: "縷",
  编: "編",
  缘: "緣",
  缠: "纏",
  缩: "縮",
  网: "網",
  罗: "羅",
  罚: "罰",
  罢: "罷",
  聂: "聶",
  聋: "聾",
  职: "職",
  联: "聯",
  肃: "肅",
  肤: "膚",
  肾: "腎",
  胀: "脹",
  胁: "脅",
  胆: "膽",
  胜: "勝",
  胶: "膠",
  脉: "脈",
  脏: "髒",
  腊: "臘",
  腾: "騰",
  舰: "艦",
  艰: "艱",
  艳: "艷",
  节: "節",
  芜: "蕪",
  芦: "蘆",
  苇: "葦",
  苏: "蘇",
  苹: "蘋",
  范: "範",
  荐: "薦",
  荣: "榮",
  荤: "葷",
  药: "藥",
  获: "獲",
  萝: "蘿",
  萧: "蕭",
  蔷: "薔",
  蕴: "蘊",
  虏: "虜",
  虑: "慮",
  虚: "虛",
  虽: "雖",
  虾: "蝦",
  蚀: "蝕",
  蚁: "蟻",
  蛮: "蠻",
  蜡: "蠟",
  衅: "釁",
  衔: "銜",
  补: "補",
  衬: "襯",
  袄: "襖",
  袜: "襪",
  装: "裝",
  裤: "褲",
  见: "見",
  观: "觀",
  规: "規",
  视: "視",
  览: "覽",
  觉: "覺",
  触: "觸",
  誉: "譽",
  誊: "謄",
  计: "計",
  订: "訂",
  讣: "訃",
  认: "認",
  讥: "譏",
  讨: "討",
  让: "讓",
  训: "訓",
  议: "議",
  讯: "訊",
  记: "記",
  讲: "講",
  讳: "諱",
  讶: "訝",
  许: "許",
  论: "論",
  讼: "訟",
  设: "設",
  访: "訪",
  证: "證",
  评: "評",
  诅: "詛",
  识: "識",
  诉: "訴",
  诊: "診",
  词: "詞",
  试: "試",
  诗: "詩",
  诛: "誅",
  话: "話",
  询: "詢",
  该: "該",
  详: "詳",
  诫: "誡",
  语: "語",
  误: "誤",
  诱: "誘",
  说: "說",
  诵: "誦",
  请: "請",
  诸: "諸",
  读: "讀",
  课: "課",
  谁: "誰",
  调: "調",
  谆: "諄",
  谈: "談",
  谋: "謀",
  谍: "諜",
  谐: "諧",
  谗: "讒",
  谚: "諺",
  谜: "謎",
  谢: "謝",
  谣: "謠",
  谦: "謙",
  谨: "謹",
  谬: "謬",
  谱: "譜",
  谴: "譴",
  贝: "貝",
  贞: "貞",
  负: "負",
  责: "責",
  贤: "賢",
  败: "敗",
  账: "賬",
  质: "質",
  贩: "販",
  贪: "貪",
  贫: "貧",
  购: "購",
  贮: "貯",
  贯: "貫",
  贰: "貳",
  贱: "賤",
  贴: "貼",
  贷: "貸",
  贸: "貿",
  费: "費",
  贺: "賀",
  贼: "賊",
  贿: "賄",
  赃: "贓",
  资: "資",
  赏: "賞",
  赔: "賠",
  赖: "賴",
  赞: "贊",
  赠: "贈",
  赵: "趙",
  赶: "趕",
  趋: "趨",
  跃: "躍",
  践: "踐",
  踊: "踴",
  踪: "蹤",
  车: "車",
  轧: "軋",
  轨: "軌",
  轩: "軒",
  转: "轉",
  轮: "輪",
  软: "軟",
  轰: "轟",
  轻: "輕",
  载: "載",
  较: "較",
  辆: "輛",
  辉: "輝",
  辑: "輯",
  输: "輸",
  辖: "轄",
  边: "邊",
  辽: "遼",
  达: "達",
  迁: "遷",
  过: "過",
  迈: "邁",
  运: "運",
  还: "還",
  这: "這",
  进: "進",
  远: "遠",
  违: "違",
  连: "連",
  迟: "遲",
  迹: "跡",
  适: "適",
  选: "選",
  逊: "遜",
  递: "遞",
  逻: "邏",
  遗: "遺",
  邓: "鄧",
  邮: "郵",
  邹: "鄒",
  邻: "鄰",
  郁: "鬱",
  郑: "鄭",
  酝: "醞",
  酱: "醬",
  酿: "釀",
  释: "釋",
  针: "針",
  钓: "釣",
  钟: "鐘",
  钢: "鋼",
  钥: "鑰",
  钮: "鈕",
  钱: "錢",
  钻: "鑽",
  铀: "鈾",
  铁: "鐵",
  铃: "鈴",
  铅: "鉛",
  铜: "銅",
  铝: "鋁",
  铡: "鍘",
  铣: "銑",
  铭: "銘",
  铱: "銥",
  铸: "鑄",
  铺: "鋪",
  销: "銷",
  锁: "鎖",
  锈: "鏽",
  锌: "鋅",
  锐: "銳",
  错: "錯",
  锥: "錐",
  键: "鍵",
  镇: "鎮",
  长: "長",
  门: "門",
  闭: "閉",
  问: "問",
  闯: "闖",
  闲: "閒",
  间: "間",
  闷: "悶",
  闸: "閘",
  闻: "聞",
  闽: "閩",
  阀: "閥",
  阁: "閣",
  阂: "閡",
  阅: "閱",
  阉: "閹",
  阎: "閻",
  阔: "闊",
  队: "隊",
  阳: "陽",
  阵: "陣",
  阶: "階",
  际: "際",
  陆: "陸",
  陈: "陳",
  陨: "隕",
  险: "險",
  随: "隨",
  隐: "隱",
  隶: "隸",
  雾: "霧",
  韵: "韻",
  页: "頁",
  顷: "頃",
  项: "項",
  顺: "順",
  须: "須",
  顾: "顧",
  顿: "頓",
  颂: "頌",
  预: "預",
  领: "領",
  颐: "頤",
  频: "頻",
  颗: "顆",
  题: "題",
  颜: "顏",
  风: "風",
  飘: "飄",
  飞: "飛",
  饥: "飢",
  饭: "飯",
  饰: "飾",
  饲: "飼",
  饵: "餌",
  馆: "館",
  馈: "饋",
  馋: "饞",
  马: "馬",
  驭: "馭",
  驱: "驅",
  驴: "驢",
  驶: "駛",
  驻: "駐",
  驾: "駕",
  骂: "罵",
  骄: "驕",
  验: "驗",
  骑: "騎",
  骗: "騙",
  骚: "騷",
  骡: "騾",
  骤: "驟",
  鲜: "鮮",
  鸟: "鳥",
  鸡: "雞",
  鸣: "鳴",
  鸦: "鴉",
  鸯: "鴦",
  鸽: "鴿",
  鹏: "鵬",
  鹤: "鶴",
  麦: "麥",
  齐: "齊",
  龄: "齡",
  龙: "龍",
  龟: "龜"
};

// src/client/convert.ts
var CHARS = zh_tw_chars_default;
var CONVERTIBLE = new Set(Object.keys(CHARS));
var CHAR_TABLE_SIZE = CONVERTIBLE.size;
function convertZhTw(text) {
  let needed = false;
  for (const ch of text) {
    if (CONVERTIBLE.has(ch)) {
      needed = true;
      break;
    }
  }
  if (!needed) return text;
  let out = "";
  for (const ch of text) out += CHARS[ch] ?? ch;
  return out;
}

// src/client/detect.ts
function resolveInitialLocale() {
  return detectBrowserLocale() ?? FALLBACK_LOCALE;
}
function detectBrowserLocale() {
  if (typeof window === "undefined") return void 0;
  for (const tag of [...navigator.languages ?? [], navigator.language]) {
    const match = matchTag(tag);
    if (match !== void 0) return match;
  }
  return void 0;
}
var TRADITIONAL_REGIONS = /* @__PURE__ */ new Set(["tw", "hk", "mo"]);
function matchTag(tag) {
  const parts = tag.toLowerCase().split("-");
  const primary = parts[0];
  if (primary === "zh") {
    if (parts.includes("hant")) return "zh-TW";
    if (parts.includes("hans")) return "zh";
    return parts.some((part) => TRADITIONAL_REGIONS.has(part)) ? "zh-TW" : "zh";
  }
  return LOCALE_IDS.find((id) => id.toLowerCase().split("-")[0] === primary);
}

// src/client/runtime.ts
var COMMON_NS = "common";
var LocaleRuntime = class {
  dicts = /* @__PURE__ */ new Map();
  bound = /* @__PURE__ */ new Map();
  snapshot;
  listeners = /* @__PURE__ */ new Set();
  ctx;
  host;
  /** Browser-derived locale standing wherever no explicit Host selection does. */
  provisional;
  /**
   * @param ctx - owning context (change events are emitted on it; the scope
   * listener is released through ctx.effect on dispose).
   * @param host - durable preference scope owned by the providing plugin;
   * absent compositions (standalone dictionary registries) stay process-local.
   */
  constructor(ctx, host) {
    this.ctx = ctx;
    this.host = host;
    this.provisional = resolveInitialLocale();
    this.snapshot = Object.freeze({ active: this.provisional, locales: LOCALES, revision: 0 });
    if (host !== void 0) {
      ctx.effect(() => host.subscribe(() => {
        this.adopt(host);
      }), "locale: settings scope adoption");
      this.adopt(host);
    }
  }
  /**
   * Read the current immutable locale snapshot.
   * @returns the current snapshot (stable reference until the next change).
   */
  getLocale() {
    return this.snapshot;
  }
  /**
   * LocaleFace getSnapshot: the current snapshot (carries `revision`; stable
   * reference between changes, uSES-safe).
   * @returns the current snapshot.
   */
  getSnapshot() {
    return this.snapshot;
  }
  /**
   * LocaleFace subscribe: notified on every snapshot change (locale switch
   * or dictionary registration — registrations bump the revision so already
   * rendered outlets pick up late-arriving dictionaries).
   * @param fn - change callback.
   * @returns unsubscribe.
   */
  subscribe(fn) {
    this.listeners.add(fn);
    return () => {
      this.listeners.delete(fn);
    };
  }
  /**
   * Switch the active locale — the only user preference write entry.
   *
   * The durable write happens even when the id already matches the active
   * locale, because the active value may be a provisional browser-derived or
   * fallback resolution that nothing has stored yet. Picking the language
   * already on screen is still an explicit choice, and it must survive a
   * different browser sharing the same DSH home. Only the render notification
   * is conditional: republishing an unchanged locale would churn every
   * subscriber for nothing.
   * @param id - a registered locale id; unknown ids throw.
   */
  setLocale(id) {
    const match = this.snapshot.locales.find((l) => l.id === id);
    if (match === void 0) throw new Error(`locale "${id}" is not registered`);
    if (this.snapshot.active !== match.id) this.publish(match.id, true);
    void this.host?.set(LOCALE_PREFERENCE_FIELD, match.id);
  }
  /**
   * Adopt the scope's accepted durable selection without writing it back; an
   * absent selection returns to the browser-derived locale.
   *
   * A stored id this roster does not ship is treated as absent rather than
   * adopted. The document key is shared with the built-in plugin, so it can
   * hold a language this fork dropped; adopting it would leave the Language
   * row with nothing selected and every lookup falling to English, with no
   * way back except editing the file. It is left on disk untouched, so
   * restoring the language restores the selection.
   * @param host - the constructor-narrowed scope driving this adoption.
   */
  adopt(host) {
    const section = host.getSnapshot().value;
    if (section === void 0) return;
    const stored = section.preference;
    const target = isShipped(stored) ? stored : this.provisional;
    if (this.snapshot.active === target) return;
    this.publish(target, true);
  }
  register(ns, localeOrDicts, dict) {
    const pairs = typeof localeOrDicts === "string" ? [[localeOrDicts, dict]] : Object.entries(localeOrDicts);
    let locales = this.dicts.get(ns);
    if (!locales) {
      locales = /* @__PURE__ */ new Map();
      this.dicts.set(ns, locales);
    }
    for (const [locale] of pairs) {
      if (locales.has(locale)) throw new Error(`locale namespace "${ns}" already has locale "${locale}"`);
    }
    for (const [locale, entries] of pairs) locales.set(locale, entries);
    this.publish(this.snapshot.active, false);
    return () => {
      const owner = this.dicts.get(ns);
      if (!owner) return;
      let removed = false;
      for (const [locale, entries] of pairs) {
        if (owner.get(locale) === entries) {
          owner.delete(locale);
          removed = true;
        }
      }
      if (removed) this.publish(this.snapshot.active, false);
    };
  }
  bind(ns) {
    let t = this.bound.get(ns);
    if (!t) {
      t = (key, params) => this.translate(ns, key, params);
      this.bound.set(ns, t);
      return t;
    }
    return t;
  }
  translate(ns, key, params) {
    const template = this.lookup(ns, key) ?? (ns !== COMMON_NS ? this.lookup(COMMON_NS, key) : void 0) ?? key;
    if (!params) return template;
    return template.replace(/\{(\w+)\}/g, (match, name2) => name2 in params ? String(params[name2]) : match);
  }
  /**
   * Resolve one key within one namespace, walking the locale rungs.
   *
   * The middle rung is the fork's addition: a zh-TW read with no curated
   * string falls to the Simplified value and converts it, which beats
   * dropping straight to English for a reader who asked for Chinese. Only
   * pairs listed in CONVERT_FALLBACK have such a rung, and a curated string
   * always wins over a converted one.
   */
  lookup(ns, key) {
    const locales = this.dicts.get(ns);
    if (locales === void 0) return void 0;
    const active = this.snapshot.active;
    const curated = locales.get(active)?.[key];
    if (curated !== void 0) return curated;
    const convertible = CONVERT_FALLBACK[active];
    if (convertible !== void 0) {
      const source = locales.get(convertible)?.[key];
      if (source !== void 0) return convertZhTw(source);
    }
    return locales.get(FALLBACK_LOCALE)?.[key];
  }
  /**
   * Advance the snapshot revision and notify LocaleFace subscribers (render
   * refresh). Only an active-locale switch additionally emits
   * `locale/change` — dictionary registrations stay off the event so
   * registration-heavy boot cannot storm event listeners (which may
   * re-register slots in response).
   */
  publish(active, localeChanged) {
    this.snapshot = Object.freeze({
      active,
      locales: this.snapshot.locales,
      revision: this.snapshot.revision + 1
    });
    if (localeChanged) this.ctx.emit("locale/change", this.snapshot);
    for (const fn of [...this.listeners]) {
      try {
        fn();
      } catch (error) {
        console.error("locale subscriber crashed:", error);
      }
    }
  }
};

// src/client/backfill.generated.json
var backfill_generated_default = {
  "zh-TW": {
    command: {
      "listbox.aria": "/{command} 相符項目",
      "notice.imagesUnsupported": "/{command} 不接受圖片附件，請先移除圖片",
      "overlay.aria": "/{command} 選項",
      "search.aria": "篩選選項",
      "search.placeholder": "搜尋…",
      "status.applying": "正在套用…",
      "status.empty": "無選項",
      "status.loading": "正在載入選項…"
    },
    conversation: {
      "access.confirm.acknowledge": "我已了解風險，並願意繼續",
      "access.confirm.description": "啟用完全權限後，智慧體將減少確認步驟，並且可以直接執行更多操作，包括敏感操作、檔案修改或外部命令。僅建議在你信任目前任務時使用。",
      "bash.running": "執行中",
      "chat.loadError": "歷史載入失敗：{message}（{code}）",
      "chat.loadOlder": "載入更早",
      "context.messages": "對話訊息",
      "details.empty": "點擊訊息流中的工具行檢視詳情",
      "details.notInWindow": "該呼叫不在目前視窗內",
      "details.running": "執行中…",
      "fileOpen.folderTitle": "無法開啟資料夾",
      "fileOpen.folderUnknown": "無法開啟此資料夾",
      "fileOpen.title": "無法開啟檔案",
      "fileOpen.unknown": "無法開啟此檔案",
      "hint.goal": "輸入目標，智慧體將持續執行",
      "hint.goal.active": "目前目標進行中。可輸入 edit 修改 / pause 暫停 / resume 繼續 / clear 清除",
      "hint.plan": "描述你的任務以生成計畫",
      "image.dropBlocked": "目前無法新增圖片",
      "image.dropTitle": "圖片拖動到此處即可新增",
      "image.loadFailed": "圖片載入失敗，點擊重試",
      "image.loading": "圖片載入中…",
      "image.modelUnsupported": "目前模型不支援圖片，請切換支援圖片的模型",
      "image.openOriginal": "檢視原圖",
      "image.openOriginalLabel": "{label}，點擊檢視原圖",
      "image.pending": "待傳送圖片",
      "image.scrollLeft": "向左捲動圖片",
      "image.scrollRight": "向右捲動圖片",
      "image.sendFailed": "圖片傳送失敗（{reason}），請重新新增圖片後再試",
      "image.subagentUnsupported": "子智慧體會話暫不支援圖片",
      "image.tooMany": "一條訊息最多新增 {count} 張圖片",
      "image.tooManyPixels": "圖片解析度過高，請壓縮後重試",
      "image.unsupportedType": "僅支援 PNG、JPG、WebP、GIF 格式的圖片",
      "input.accessMode": "訪問模式，目前：{name}",
      "input.send": "傳送訊息",
      "json.truncated": "… 已截斷，共 {total} 字元",
      "message.branchUnavailable": "僅可從已完成輪次的最後一條訊息分支",
      "message.compaction.expand": "點擊檢視壓縮摘要",
      "message.context.catalog.replaced": "取代目錄",
      "message.maxTokens.hint": "回答被截斷，已有輸出保留在對話中。傳送“繼續”可讓模型接著輸出。",
      "message.turnError": "本輪執行失敗",
      "placeholder.default": "給智慧體發訊息",
      "placeholder.hero": "描述你想要建置的內容",
      "placeholder.parentOffline": "父會話已離線，無法繼續傳送；仍可停止目前執行",
      "placeholder.plan": "描述你的任務以生成計畫",
      "placeholder.steerQueue": "Cmd/Ctrl+Enter 插話傳送全部排隊訊息",
      "queue.count": "{n} 條排隊訊息",
      "queue.edit": "編輯排隊訊息",
      "queue.edit.unsupported": "包含非文字內容，暫不支援編輯",
      "queue.editFailed": "編輯失敗：這條訊息可能已經開始傳送。",
      "queue.remove": "刪除排隊訊息",
      "queue.removeFailed": "刪除失敗：這條訊息可能已經開始傳送。",
      "queue.save": "儲存排隊訊息",
      "queue.steer": "插話傳送",
      "queue.steer.unavailable": "僅執行中可插話傳送",
      "queue.steerFailed": "插話傳送失敗，請重試。",
      "row.running": "執行中",
      "settings.enter.description": "僅在智慧體執行時生效；Cmd/Ctrl+Enter 使用另一行為",
      "settings.enter.queue": "排隊傳送",
      "settings.enter.steer": "插話傳送",
      "stats.cacheHit": "快取命中 {percent}%",
      "stats.toolCall": "工具呼叫 {duration}",
      "terminal.exitCode": "結束代碼 {code}",
      "terminal.expandAria": "展開其餘 {n} 行輸出",
      "terminal.expandRest": "… 其餘 {n} 行",
      "terminal.running": "執行中"
    },
    deliverables: {
      "produced.label": "產物",
      "produced.more": "+ {count} 個檔案",
      "produced.moreOne": "+ 1 個檔案",
      "produced.open": "開啟 {name}",
      "produced.showInFolder": "在資料夾中顯示"
    },
    "directory-browser": {
      "browser.create": "建立",
      "browser.createIn": '在"{name}"中新增資料夾',
      "browser.folderName": "資料夾名稱",
      "browser.loading": "載入中…",
      "browser.newFolder": "新增資料夾",
      "browser.open": "開啟",
      "browser.showHidden": "顯示隱藏檔案",
      "browser.truncated": "資料夾過多，僅顯示開頭部分。",
      "browser.untitledFolder": "未命名資料夾"
    },
    feedback: {
      "error.conflict": "這條回饋已在別處改動，已顯示最新狀態",
      "error.generic": "回饋儲存失敗",
      "error.load": "回饋狀態載入失敗",
      "note.aria": "回饋說明",
      "note.dialog": "回饋",
      "note.placeholder": "這條回答哪裡好，或哪裡有問題？（可選）",
      "note.save": "儲存"
    },
    goal: {
      "action.resume": "恢復目標",
      "action.save": "儲存目標"
    },
    job: {
      "count.idle.one": "{count} 個背景任務",
      "count.idle.other": "{count} 個背景任務",
      "count.live.one": "{count} 個背景任務執行中",
      "count.live.other": "{count} 個背景任務執行中",
      "duration.title.live": "已執行 {duration}",
      "list.aria": "背景任務",
      "status.running": "執行中"
    },
    model: {
      "action.reload": "重新載入",
      "blocked.composer": "目前模型不可用，請先選擇模型",
      "empty.efforts": "目前模型未提供推理等級。",
      "option.loadError": "目錄載入失敗：{message}",
      "status.loading": "正在重新整理模型列表…",
      "trigger.aria": "選擇模型，目前 {model}",
      "trigger.ariaEffort": "選擇模型，目前 {model}，推理等級 {effort}",
      "warning.groupLoad": "{name} 載入失敗：{message}"
    },
    "permission.access": {
      "confirm.acknowledge": "我已了解風險，並願意繼續",
      "confirm.description": "啟用完全權限後，智慧體將減少確認步驟，並且可以直接執行更多操作，包括敏感操作、檔案修改或外部命令。僅建議在你信任目前任務時使用。"
    },
    plan: {
      "chip.off.aria": "plan mode 已關閉，按下開啟",
      "chip.off.title": "plan mode 已關閉 — 點擊開啟（/plan）",
      "chip.on.aria": "plan mode 已開啟，按下關閉",
      "chip.on.title": "plan mode 已開啟 — 點擊關閉（/plan off）"
    },
    question: {
      "error.unanswered": "請選擇一個選項或填寫自訂答案。",
      "plan.discuss": "去聊天裡說",
      "plan.header": "計畫待審"
    },
    reference: {
      "candidate.file": "檔案",
      "candidate.folder": "資料夾",
      "section.files": "檔案與資料夾"
    },
    "settings.agentPreset": {
      brokenBadge: "載入失敗",
      brokenNoCopy: "預設載入失敗，不能複製",
      builtIn: "內建",
      builtInGroup: "內建",
      copyIntro: "整個預設會在本機複製一份。識別碼將成為目錄名，事後無法更改；其餘內容之後直接在預設自己的檔案裡編輯。",
      copyOf: "複製自",
      copyTitle: "複製預設",
      create: "建立",
      creating: "正在建立…",
      creatorDraft: "用「創造模式」創作自訂預設",
      customGroup: "自訂",
      deleteDescription: "預設目錄將被刪除。已在其上執行的會話不受影響；新會話將無法再選擇它。",
      description: "對此後新增的會話生效。執行中的會話保持它開始時的預設。",
      displayNamePlaceholder: "選擇器中顯示的名字，預設用識別碼",
      duplicate: "複製",
      duplicateUnavailable: "此部署未設定可寫的預設目錄",
      error: "無法載入 Agent 預設。",
      headerHint: "本會話執行的 Agent 預設，開始時即固定",
      idInvalid: "只能使用小寫字母、數字與連字元，且以字母或數字開頭。",
      idRequired: "請填寫識別碼。",
      idTaken: "該識別碼已被佔用。",
      inUse: "目前使用",
      loading: "正在載入預設…",
      openLocation: "開啟目錄",
      presetCodeDescription: "具備標準模式的全部能力，並透過 Code Mode SDK 呈現工具，讓模型用一個 TypeScript 程式組合多步操作。",
      presetCordisDescription: "用於建立自訂 Agent preset：具備標準模式的全部能力，並提供執行時檢查、外掛實驗和 preset 創作指導。",
      presetId: "識別碼",
      presetStandardDescription: "功能完整的編碼 Agent，支援檔案編輯、Shell、檔案與網頁檢索、Skills、計畫、目標、子代理和工作流。",
      revealedPathLabel: "預設檔案：",
      sectionIntro: "預設即一個會話的 Agent 所執行的外掛組裝 —— 它的工具、提示詞與能力。複製一份既有預設改成自己的，或用「創造模式」讓 Agent 幫你建立。",
      setDefault: "設為預設",
      showLocation: "檢視路徑",
      userTrust: "自訂",
      view: "檢視"
    },
    settings: {
      close: "關閉",
      "general.nav": "一般設定",
      openDocument: "開啟設定檔",
      "openDocument.error": "無法開啟設定檔",
      title: "設定",
      trigger: "設定"
    },
    "settings.models": {
      add: "新增供應商",
      addModel: "新增模型",
      advancedHint: "其餘欄位位於 settings.yaml，請直接編輯該區段。",
      apply: "套用",
      applying: "正在套用…",
      baseUrl: "基礎網址",
      baseUrlDefault: "供應商預設值",
      cancel: "取消",
      close: "關閉",
      conflict: "這張卡片開啟期間，有人變更了這些設定。請關閉後重新開啟以編輯目前的值。",
      contextWindow: "上下文視窗",
      contextWindowPlaceholder: "使用供應商預設值",
      create: "建立供應商",
      creating: "正在建立…",
      credentialConfigured: "已設定 API 金鑰",
      credentialMissing: "缺少 API 金鑰",
      customAdd: "新增自訂供應商",
      customApi: "API 通訊協定",
      customApiUnset: "未選擇",
      customDisplayName: "顯示名稱",
      customNeedsBaseUrl: "自訂供應商需要基礎網址。",
      customNeedsModels: "自訂供應商至少需要一個模型。",
      customRoute: "供應商 ID",
      customRouteHint: "小寫識別碼，以英文字母開頭，用於在請求中唯一指名此供應商，並作為其憑證名稱。",
      customRouteInvalid: "請以小寫英文字母開頭，其後只能是小寫字母、數字與連字號。",
      customRouteTaken: "已有供應商使用這個 ID。",
      customTag: "自訂",
      customTitle: "自訂供應商",
      customized: "自訂設定",
      deleteConfirm: "刪除 {provider}",
      deleteDescription: "刪除 {provider} 會移除它的設定。它所用的憑證由別處管理，將會保留。",
      deleteDescriptionWithCredential: "刪除 {provider} 會移除它的設定與已儲存的 API 金鑰。",
      deleteTitle: "刪除 {provider}？",
      deleting: "正在刪除 {provider}…",
      edit: "編輯",
      editProvider: "編輯 {provider}",
      fetchAdopt: "新增所選項目",
      fetchDescription: "以下是此供應商可用的模型，請選擇要新增的項目。",
      fetchDeselectAll: "取消全選",
      fetchEmpty: "此供應商未列出任何模型，請手動新增。",
      fetchModels: "取得可用模型",
      fetchNeedsBaseUrl: "請先輸入基礎網址，再取得模型。",
      fetchSelectAll: "全選",
      fetchTitle: "選擇要新增的模型",
      fetching: "正在詢問供應商…",
      intro: "輸入 API 金鑰即可使用下列供應商的模型。",
      keyBlank: "輸入 API 金鑰，或留空以沿用已儲存的金鑰。",
      keyBlankNew: "輸入 API 金鑰；若此供應商以其他方式驗證，則可留空。",
      keyEnvLocked: "由啟動環境提供（唯讀）",
      keyIllegalCharacters: "這組 API 金鑰的格式無效，請檢查。",
      keyInput: "API 金鑰",
      keyPlaceholder: "輸入你的 API 金鑰",
      keyPlaceholderNative: "輸入 API 金鑰，或留空以改用環境驗證",
      keyRequired: "請輸入 API 金鑰以繼續。",
      keyStored: "已設定——輸入新值即可取代",
      loadFailed: "載入供應商目錄失敗",
      maxTokens: "最大輸出 token 數",
      maxTokensPlaceholder: "使用供應商預設值",
      model: "模型",
      modelAdvanced: "容量",
      modelCapacityInvalid: "容量必須是數字，可加上 K 或 M 字尾。",
      modelContextInvalid: "上下文視窗必須是正數，例如 131072、256K 或 1M。",
      modelContextWindow: "上下文視窗",
      modelDuplicate: "每個模型 ID 只能出現一次。",
      modelId: "模型 ID",
      modelIdDuplicate: "模型 ID 不可重複。",
      modelIdRequired: "模型 ID 為必填。",
      modelMaxTokens: "最大輸出 token 數",
      modelMaxTokensInvalid: "最大輸出 token 數必須是正數，例如 8192、64K 或 1M。",
      modelName: "顯示名稱",
      modelNameInvalid: "顯示名稱不可為空。",
      modelNamePlaceholder: "留空時使用模型 ID",
      models: "模型",
      modelsCustomized: "自訂模型目錄",
      modelsEmpty: "選擇器中將不會顯示任何模型。未列出的 ID 仍可直接送出。",
      modelsInherited: "使用配接器預設值",
      nav: "模型",
      onboardingDescription: "設定官方 DeepSeek 供應商，即可開始打造。",
      onboardingLater: "稍後設定",
      onboardingSave: "儲存並繼續",
      onboardingSaving: "正在儲存…",
      onboardingTitle: "新增 API 金鑰即可開始",
      provider: "供應商",
      readOnly: "此部署中的設定檔為唯讀。",
      remove: "刪除",
      removeModel: "刪除模型",
      removeProvider: "刪除 {provider}",
      resetModels: "還原預設值",
      retry: "重試",
      savedProvider: "已儲存 {provider}。",
      title: "模型",
      welcomeBody: "DeepSeek Harness 0.1 仍在為 Harness 開發者進行測試。許多地方仍待改進，我們歡迎開發者社群提供回饋。DeepSeek Harness 的核心外掛與基礎 API 在未來數個月內仍會快速演進。\n\n我們期待與世界各地的開發者一同探索智慧的極限，並以開源、開放、可重複使用且可組合的基礎設施為根基。歡迎各地的 Harness 開發者加入 DSH 外掛生態系。",
      welcomeContinue: "繼續",
      welcomeError: "無法儲存這項確認，請再試一次。",
      welcomeTitle: "內部測試聲明"
    },
    "settings.permission": {
      "confirm.acknowledge": "我已了解風險，並願意繼續",
      "confirm.description": "啟用完全權限後，新會話將減少確認步驟，並且可以直接執行更多操作，包括敏感操作、檔案修改或外部命令。僅建議在你信任後續任務時使用。",
      description: "選擇新會話的預設權限模式",
      loading: "載入中"
    },
    "settings.pluginInventory": {
      catalog: "外掛列表",
      configuration: "設定狀態",
      empty: "暫無外掛。",
      emptySearch: "沒有相符的外掛。",
      error: "暫時無法讀取外掛。",
      loading: "正在讀取外掛…",
      loadingPhase: "載入中",
      search: "搜尋外掛",
      tab: "外掛列表",
      unloading: "解除安裝中"
    },
    "settings.plugins": {
      agentLoopDescription: "Agent 如何派發工具呼叫。",
      agentLoopMaxParallel: "並行工具呼叫數",
      agentLoopMaxParallelHint: "同一步內最多同時執行多少個可並行的呼叫。",
      bashDescription: "限制 agent 執行的每一條命令。",
      bashMaxOutputBytes: "單流輸出上限（位元組）",
      bashMaxOutputBytesHint: "超出部分會轉存到臨時檔案，而不是被丟棄。",
      bashTimeoutMs: "命令逾時（毫秒）",
      bashTimeoutMsHint: "單條命令允許執行多久，逾時即終止。",
      bashTitle: "終端機",
      collapse: "收起設定",
      configurableTab: "外掛設定",
      empty: "本部署沒有開放任何外掛設定。",
      expand: "展開設定",
      intro: "設定和檢視本部署已安裝的外掛。",
      invalidNumber: "請填數字；留空表示使用預設值。",
      nav: "外掛",
      readOnly: "本部署的設定為唯讀。",
      reset: "恢復預設",
      save: "儲存",
      saving: "儲存中…",
      tabs: "外掛檢視",
      title: "外掛",
      unsaved: "未儲存",
      webSearchApiKeyHint: "不寫入設定檔案。留空表示保持目前密鑰。",
      webSearchApiKeySet: "已設定密鑰。",
      webSearchApiKeyUnset: "未設定密鑰；設定之前搜尋不可用。",
      webSearchBaseUrl: "端點網址",
      webSearchBaseUrlHint: "留空則使用提供者預設地址。",
      webSearchDescription: "DeepSeek 搜尋提供者。",
      webSearchMaxUses: "單次請求最多搜尋次數",
      webSearchMaxUsesHint: "一次請求在必須作答前最多可以搜尋多少次。",
      webSearchTitle: "網頁搜尋"
    },
    sidebar: {
      "session.new": "新對話",
      "session.new.label": "新增會話",
      "toggle.collapse": "收合側邊欄",
      "toggle.open": "開啟側邊欄"
    },
    skill: {
      "menu.userOnly": "僅使用者",
      "row.failed": "skill 載入失敗",
      "row.instructions": "說明",
      "row.running": "正在載入 skill",
      "row.stopped": "skill 載入已中止"
    },
    "slash.menu": {
      command: "命令",
      loading: "正在載入…",
      skill: "技能",
      subagent: "子代理",
      "suggestions.aria": "觸發候選建議"
    },
    subagent: {
      "activity.inactive": "目前未執行",
      "activity.running": "正在執行",
      "count.running.one": "{count} 個子代理，正在執行",
      "count.running.other": "{count} 個子代理，正在執行",
      "diagnostic.unsupported": "子代理記錄版本不受支援",
      "load.error": "無法載入子代理",
      "loading.aria": "正在載入子代理",
      "loading.label": "正在載入子代理…",
      "readonly.body": "父會話目前不在線，重新開啟父會話後即可繼續傳送訊息。",
      "readonly.oneShot.body": "一次性任務不支援後續訊息，可在這裡檢視完整執行記錄。",
      "readonly.title": "此子代理暫時唯讀"
    },
    trajectory: {
      "toolbar.aria": "軌跡工具列",
      "toolbar.search": "搜尋軌跡",
      "toolbar.searchPlaceholder": "搜尋"
    },
    workflowRun: {
      "member.open": "開啟 {name}",
      "status.running": "執行中",
      "statusCount.running": "執行中 {count}"
    },
    workspace: {
      "actions.newSession.aria": "在“{name}”中新增會話",
      "delete.desc": "將把“{name}”從工作區列表中移除。資料夾與會話記錄會保留，其會話將顯示在“未分組”下。",
      "empty.noMatches": "無相符結果",
      "folderError.title": "無法開啟資料夾",
      "hover.copied": "已複製",
      "hover.created": "建立於 {time}",
      "menu.addWorkspace": "新增工作區…",
      "menu.archiveSession": "封存會話",
      "picker.loading": "正在載入工作區…",
      "search.clear": "清除搜尋",
      "search.hasMore": "僅顯示前 {n} 條結果，請縮小搜尋範圍。",
      "search.noMatches": "無相符會話",
      "search.pending": "正在搜尋會話歷史…",
      "search.placeholder": "搜尋會話…",
      "search.results.aria": "搜尋結果",
      "search.sessions.aria": "搜尋會話",
      "search.unavailable": "內容搜尋暫不可用，僅顯示名稱相符。",
      "sessions.expand": "展開其餘 {n} 個會話",
      "status.planReview": "計畫待審",
      "status.subagentsRunning.one": "{n} 個子代理執行中",
      "status.subagentsRunning.other": "{n} 個子代理執行中",
      "viewOptions.label": "檢視選項",
      "workspace.add": "新增工作區"
    }
  },
  ja: {
    command: {
      "search.placeholder": "検索…",
      "search.aria": "選択肢を絞り込む",
      "status.loading": "選択肢を読み込み中…",
      "status.applying": "適用中…",
      "status.empty": "選択肢がありません",
      "overlay.aria": "/{command} の選択肢",
      "listbox.aria": "/{command} の一致項目",
      "notice.imagesUnsupported": "/{command} は画像の添付に対応していません。先に画像を削除してください"
    },
    conversation: {
      "access.confirm.acknowledge": "リスクを理解した上で続行します",
      "access.confirm.cancel": "キャンセル",
      "access.confirm.description": "フルアクセスでは確認の手順が減り、エージェントが機密性の高い操作、ファイルの変更、外部コマンドの実行を含む多くの操作を直接実行できるようになります。現在のタスクを信頼できる場合にのみ使用してください。",
      "access.confirm.enable": "フルアクセスを有効にする",
      "access.confirm.title": "フルアクセスを有効にしますか？",
      "approval.allowOnce": "1 回だけ許可",
      "approval.detail.aria": "承認の詳細",
      "approval.escalation": "ツール {toolName} が特権付きの実行を要求しています",
      "approval.reject": "拒否",
      "approval.waiting": "承認待ち",
      "ask.answered": "{answered}/{total} 件回答済み",
      "ask.cancelled": "キャンセル済み",
      "ask.interrupted": "中断",
      "ask.rowTitle": "質問する",
      "ask.waiting": "待機中",
      "bash.failed": "失敗",
      "bash.running": "実行中",
      "bash.stopped": "停止",
      "chat.loadError": "履歴を読み込めませんでした: {message} ({code})",
      "chat.loadOlder": "以前の分を読み込む",
      "chat.loadingHistory": "履歴を読み込み中…",
      "chat.toBottom": "最新に戻る",
      "clock.md": "{m}/{d}",
      "clock.ymd": "{y}/{m}/{d}",
      "command.done": "完了",
      "command.failed": "コマンドが失敗しました",
      "command.imagesUnsupported": "/{command} は画像の添付を受け付けません。先に削除してください",
      "command.running": "実行中…",
      "command.title": "コマンド",
      "context.aria": "コンテキストの {percent} を使用",
      "context.messages": "メッセージ",
      "context.system": "システムプロンプト",
      "context.tools": "ツール",
      "context.used": "のコンテキストを使用",
      "details.close": "詳細を閉じる",
      "details.empty": "メッセージ内のツール行をクリックすると詳細が表示されます",
      "details.input": "入力",
      "details.notInWindow": "この呼び出しは現在の表示範囲の外にあります",
      "details.output": "出力",
      "details.running": "実行中…",
      "details.title": "詳細",
      "duration.minutes": "{minutes}分{seconds}秒",
      "duration.seconds": "{seconds}秒",
      "fileOpen.folderTitle": "フォルダを開けませんでした",
      "fileOpen.folderUnknown": "このフォルダは開けませんでした",
      "fileOpen.title": "ファイルを開けませんでした",
      "fileOpen.unknown": "このファイルは開けませんでした",
      "hero.chooseWorkspace": "ワークスペースを選択",
      "hero.headline": "Into the Unknown",
      "hero.preview": "プレビュー",
      "hint.goal": "長時間かかるタスクの目的を説明してください",
      "hint.goal.active": "ゴール設定中 — 編集 / 一時停止 / 再開 / クリア",
      "hint.plan": "タスクを説明するとプランを作成します",
      "image.closePreview": "元の画像のプレビューを閉じる",
      "image.dimensionTooLarge": "画像の辺は {size}px までです。縮小してから再試行してください",
      "image.dropBlocked": "現在は画像を追加できません",
      "image.dropDesc": "最大 {count} 枚、1 枚あたり {size} まで",
      "image.dropTitle": "画像をここにドラッグして追加",
      "image.fileTooLarge": "画像は 1 枚あたり {size} 未満にしてください",
      "image.label": "画像",
      "image.loadFailed": "画像を読み込めませんでした。クリックで再試行します",
      "image.loading": "画像を読み込み中…",
      "image.modelUnsupported": "現在のモデルは画像に対応していません。対応するモデルに切り替えてください",
      "image.openOriginal": "原寸で表示",
      "image.openOriginalLabel": "{label}、クリックで原寸表示",
      "image.original": "元の画像",
      "image.pending": "送信待ちの画像",
      "image.preview": "元の画像のプレビュー",
      "image.remove": "画像 {name} を削除",
      "image.scrollLeft": "画像を左にスクロール",
      "image.scrollRight": "画像を右にスクロール",
      "image.sendFailed": "画像の送信に失敗しました（{reason}）。追加し直して再試行してください",
      "image.serviceUnavailable": "画像読み込みサービスを利用できません",
      "image.subagentUnsupported": "サブエージェントのセッションはまだ画像に対応していません",
      "image.tooMany": "1 通のメッセージに含められる画像は {count} 枚までです",
      "image.tooManyPixels": "画像の解像度が高すぎます。圧縮してから再試行してください",
      "image.totalTooLarge": "画像の合計が {size} を超えています。いくつか削除してから再試行してください",
      "image.unsupportedType": "対応している画像形式は PNG、JPG、WebP、GIF のみです",
      "input.accessMode": "アクセスモード、現在: {name}",
      "input.commands": "コマンド",
      "input.send": "メッセージを送信",
      "input.stop": "生成を停止",
      "json.truncated": "… 切り詰めました。全 {total} 文字",
      "message.branch": "ここから新しい会話に分岐",
      "message.branchUnavailable": "完了したターンの最後のメッセージでのみ利用できます",
      "message.compaction": "コンテキストを圧縮しました",
      "message.compaction.completed": "履歴 {items} 件を圧縮しました（約 {tokens} トークン）",
      "message.compaction.expand": "圧縮の要約を表示",
      "message.compaction.running": "コンテキストを圧縮中…",
      "message.compaction.unavailable": "圧縮の要約を利用できません",
      "message.context.catalog.more": "… 他 {count} 件",
      "message.context.catalog.replaced": "置き換え後のカタログ",
      "message.context.instructions.added": "追加",
      "message.context.instructions.loaded": "読み込み",
      "message.context.instructions.removed": "削除",
      "message.context.instructions.updated": "更新",
      "message.context.recall.counts": "{retained} 件保持 · {omitted} 件除外",
      "message.context.recall.truncated": "切り詰めました",
      "message.context.relay.from": "セッション {session} から",
      "message.context.snapshot.supersedes": "以前のスナップショットを置き換えます",
      "message.contextInjection": "コンテキストの注入",
      "message.contextRecall": "セッションの呼び出し",
      "message.extraBlock": "追加のコンテンツブロック",
      "message.maxTokens": "出力トークンの上限に達しました",
      "message.maxTokens.hint": "返答は途中で打ち切られましたが、それまでの出力は会話に残っています。「continue」と送るとモデルが続きから再開します。",
      "message.ranFor": "実行時間 {duration}",
      "message.referenceSeparator": "、",
      "message.referenceSummary": "参照したセッション · {labels}",
      "message.retry.active": "モデルへのリクエストを再試行中",
      "message.retry.cancelled": "モデルへのリクエストの再試行を中止しました",
      "message.retry.delay": "再試行までの待ち時間: ",
      "message.retry.failure": "失敗の理由: ",
      "message.retry.scheduled": "モデルへのリクエストの再試行を待機中",
      "message.retry.started": "モデルへのリクエストを再試行しました",
      "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}秒",
      "message.stopped": "停止しました",
      "message.tokensPerSecond": "{tps} tok/s",
      "message.ttft": "TTFT {seconds}秒",
      "message.turnError": "このターンは失敗しました",
      "message.unknownBlock": "不明なコンテンツブロック",
      "message.unknownSurface": "不明な表示イベント: {type}",
      "placeholder.default": "エージェントにメッセージを送る",
      "placeholder.hero": "作りたいものを説明してください",
      "placeholder.parentOffline": "親セッションがオフラインです。送信はできませんが、実行の停止は可能です",
      "placeholder.plan": "タスクを説明するとプランを作成します",
      "placeholder.steerQueue": "Cmd/Ctrl+Enter でキュー内のメッセージをすべて反映します",
      "placeholder.unavailable": "セッションを利用できません",
      "placeholder.workspace": "ワークスペースを選んで開始してください",
      "queue.cancelEdit": "編集をキャンセル",
      "queue.count": "キューに {n} 件のメッセージ",
      "queue.edit": "キュー内のメッセージを編集",
      "queue.edit.unsupported": "テキスト以外の内容を含むため、編集にはまだ対応していません",
      "queue.editFailed": "編集できませんでした。このメッセージはすでに送信が始まっている可能性があります。",
      "queue.remove": "キュー内のメッセージを削除",
      "queue.removeFailed": "削除できませんでした。このメッセージはすでに送信が始まっている可能性があります。",
      "queue.save": "キュー内のメッセージを保存",
      "queue.steer": "キュー内のメッセージで軌道修正",
      "queue.steer.unavailable": "軌道修正はエージェントの実行中のみ利用できます",
      "queue.steerFailed": "軌道修正に失敗しました。もう一度お試しください。",
      "row.failed": "失敗",
      "row.running": "実行中",
      "row.stopped": "停止",
      "session.hierarchy": "セッションの階層",
      "settings.enter.description": "実行中のみ適用されます。Cmd/Ctrl+Enter はもう一方の動作になります",
      "settings.enter.queue": "キューに入れる",
      "settings.enter.steer": "軌道修正する",
      "settings.enter.title": "実行中の Enter の動作",
      "stats.cacheHit": "キャッシュヒット {percent}%",
      "stats.counts": "{turns} ターン · {steps} ステップ",
      "stats.llm": "LLM {duration}",
      "stats.tokens": "入力 {input} tok · 出力 {output} tok",
      "stats.tokensPerSecond": "{throughput} tok/s",
      "stats.toolCall": "ツール呼び出し {duration}",
      "stats.ttftAverage": "TTFT 平均 {duration}",
      "terminal.collapseAria": "出力を折りたたむ",
      "terminal.done": "完了",
      "terminal.exitCode": "終了コード {code}",
      "terminal.expandAria": "残り {n} 行の出力を展開",
      "terminal.expandRest": "… 他 {n} 行",
      "terminal.failed": "失敗",
      "terminal.noOutput": "出力はありません",
      "terminal.running": "実行中",
      "terminal.signal": "シグナル {signal}",
      "todo.completed": "{done}/{total} 件完了",
      "todo.progress.active": "{active} 件進行中",
      "todo.progress.done": "{done} 件完了",
      "todo.progress.pending": "{pending} 件未着手",
      "todo.rowTitle": "To-do リストを更新",
      "todo.title": "To-do",
      "view.chat": "チャット"
    },
    deliverables: {
      "produced.label": "成果物",
      "produced.moreOne": "+ 1 件のファイル",
      "produced.more": "+ {count} 件のファイル",
      "produced.open": "{name} を開く",
      "produced.showInFolder": "フォルダーに表示"
    },
    "directory-browser": {
      "browser.title": "ワークスペースのディレクトリを選択",
      "browser.home": "ホーム",
      "browser.newFolder": "新規フォルダ",
      "browser.folderName": "フォルダ名",
      "browser.createIn": "「{name}」内に新規フォルダ",
      "browser.untitledFolder": "名称未設定フォルダ",
      "browser.create": "作成",
      "browser.cancel": "キャンセル",
      "browser.open": "開く",
      "browser.editPath": "パスを編集",
      "browser.loading": "読み込み中…",
      "browser.truncated": "フォルダが多すぎるため、先頭のみ表示しています。",
      "browser.showHidden": "隠しファイルを表示"
    },
    feedback: {
      "action.like": "良い回答",
      "action.likeActive": "評価を取り消す",
      "action.dislike": "良くない回答",
      "action.dislikeActive": "評価を取り消す",
      "note.open": "メモを追加",
      "note.dialog": "フィードバック",
      "note.placeholder": "良かった点、または問題だった点を教えてください（任意）",
      "note.save": "保存",
      "note.cancel": "キャンセル",
      "note.aria": "フィードバックのメモ",
      "error.conflict": "このフィードバックは別の場所で変更されました。最新の状態を表示しています",
      "error.load": "フィードバックを読み込めませんでした",
      "error.generic": "フィードバックを保存できませんでした"
    },
    goal: {
      "phase.active": "進行中のゴール",
      "phase.paused": "一時停止中のゴール",
      "phase.blocked": "ブロック中のゴール",
      "objective.aria": "ゴールの目的",
      "commandInput.aria": "コマンド入力",
      "action.save": "ゴールを保存",
      "action.cancel": "編集をキャンセル",
      "action.pause": "ゴールを一時停止",
      "action.resume": "ゴールを再開",
      "action.edit": "ゴールを編集",
      "action.clear": "ゴールをクリア"
    },
    job: {
      "count.live.one": "バックグラウンドジョブ {count} 件を実行中",
      "count.live.other": "バックグラウンドジョブ {count} 件を実行中",
      "count.idle.one": "バックグラウンドジョブ {count} 件",
      "count.idle.other": "バックグラウンドジョブ {count} 件",
      "list.aria": "バックグラウンドジョブ",
      "status.running": "実行中",
      "status.stopping": "停止中",
      "status.completed": "完了",
      "status.killed": "キャンセル済み",
      "status.failed": "失敗",
      "duration.seconds": "{seconds}秒",
      "duration.minutes": "{minutes}分{seconds}秒",
      "duration.hours": "{hours}時間{minutes}分",
      "duration.title.live": "{duration} 実行中",
      "duration.title.done": "所要時間 {duration}"
    },
    model: {
      "command.description": "この会話で使うモデルを選択します",
      "option.loadError": "カタログを読み込めませんでした: {message}",
      "trigger.fallback": "モデルを選択",
      "trigger.selectAria": "モデルを選択",
      "trigger.aria": "モデルを選択、現在は {model}",
      "trigger.ariaEffort": "モデルを選択、現在は {model}、推論の深さ {effort}",
      "menu.aria": "モデルと推論の深さ",
      "menu.model": "モデル",
      "menu.effort": "推論の深さ",
      "effort.providerDefault": "既定",
      "status.loading": "モデル一覧を更新中…",
      "error.action": "モデルの操作に失敗しました: {message}",
      "action.reload": "再読み込み",
      "warning.groupLoad": "{name} を読み込めませんでした: {message}",
      "empty.models": "利用できるモデルがありません。",
      "blocked.composer": "このモデルは利用できません。別のモデルを選択してください",
      "empty.efforts": "このモデルには推論の深さの選択肢がありません。"
    },
    "permission.access": {
      "confirm.acknowledge": "リスクを理解した上で続行します",
      "confirm.cancel": "キャンセル",
      "confirm.description": "フルアクセスでは確認の手順が減り、エージェントが機密性の高い操作、ファイルの変更、外部コマンドの実行を含む多くの操作を直接実行できるようになります。現在のタスクを信頼できる場合にのみ使用してください。",
      "confirm.enable": "フルアクセスを有効にする",
      "confirm.title": "フルアクセスを有効にしますか？"
    },
    plan: {
      "chip.on.aria": "plan mode オン、押すとオフになります",
      "chip.on.title": "plan mode オン — クリックでオフ（/plan off）",
      "chip.off.aria": "plan mode オフ、押すとオンになります",
      "chip.off.title": "plan mode オフ — クリックでオン（/plan）"
    },
    question: {
      "error.incomplete": "先にこの質問に回答してください。",
      "error.unanswered": "選択肢を選ぶか、自由入力で回答してください。",
      "nav.prev": "前の質問",
      "nav.next": "次の質問",
      "nav.minimize": "質問カードを折りたたむ",
      "nav.maximize": "質問カードを展開",
      "nav.cancel": "すべての質問を閉じる",
      "option.recommended": "おすすめ",
      "custom.placeholder": "回答を入力",
      "action.skip": "この質問をスキップ",
      "action.next": "次へ",
      "plan.header": "プランの確認",
      "plan.approve": "承認",
      "plan.decline": "却下",
      "plan.discuss": "相談する"
    },
    reference: {
      "section.files": "ファイルとフォルダ",
      "section.sessions": "セッションの会話",
      "candidate.file": "ファイル",
      "candidate.folder": "フォルダ",
      "candidate.session": "セッション",
      "candidate.noCwd": "（作業ディレクトリなし）"
    },
    "settings.agentPreset": {
      title: "エージェントプリセット",
      description: "これ以降に開始するセッションに適用されます。実行中のセッションは開始時のプリセットのままです。",
      loading: "プリセットを読み込み中…",
      error: "エージェントプリセットを読み込めませんでした。",
      userTrust: "カスタム",
      seatHint: "これから開始するセッションのエージェントプリセット",
      headerHint: "このセッションが実行しているエージェントプリセット。開始時に固定されます",
      nav: "エージェントプリセット",
      sectionIntro: "プリセットとは、セッションのエージェントが実行するプラグイン構成のことです。ツール、プロンプト、機能がここで決まります。既存のものを複製して自分用に仕上げるか、クリエイターモードでエージェントに下書きさせることもできます。",
      builtIn: "組み込み",
      setDefault: "既定に設定",
      view: "表示",
      presetStandardName: "標準モード",
      presetStandardDescription: "ファイル編集、シェル、ファイル検索とウェブ検索、スキル、プランニング、ゴール、サブエージェント、ワークフローを備えたフル機能のコーディングエージェントです。",
      presetCodeName: "PTC モード",
      presetCodeDescription: "標準モードの全機能に加え、ツールを Code Mode SDK 経由で公開します。モデルは複数ステップの操作を 1 つの TypeScript プログラムにまとめられます。",
      presetMinimalName: "ミニマルモード",
      presetMinimalDescription: "永続 bash と str_replace_editor の 2 つのツールだけを使うコーディングエージェントです。",
      presetCordisName: "クリエイターモード",
      presetCordisDescription: "カスタムのエージェントプリセットを作るためのモードです。標準モードの全機能に加え、ランタイムの調査、プラグインの実験、プリセット作成のガイドが使えます。",
      duplicate: "複製",
      duplicateUnavailable: "このデプロイには書き込み可能なプリセットディレクトリがありません",
      delete: "削除",
      presetId: "識別子",
      presetIdPlaceholder: "my-agent",
      displayName: "名前",
      displayNamePlaceholder: "選択画面に表示されます。未入力の場合は識別子が使われます",
      inUse: "使用中",
      builtInGroup: "組み込み",
      customGroup: "カスタム",
      noDescription: "説明はありません。",
      brokenBadge: "読み込み失敗",
      brokenNoCopy: "読み込みに失敗したプリセットは複製できません",
      copyOf: "複製元",
      composition: "構成 (agent.cordis.yml)",
      cancel: "キャンセル",
      close: "閉じる",
      retry: "再試行",
      copyTitle: "プリセットを複製",
      copyIntro: "プリセット全体がこのマシン上に複製されます。識別子はそのディレクトリ名になり、後から変更できません。それ以外はプリセット自身のファイルで編集します。",
      create: "作成",
      creating: "作成中…",
      creatorDraft: "クリエイターモードでカスタムプリセットを下書きする",
      openLocation: "フォルダを開く",
      showLocation: "場所を表示",
      revealedPathLabel: "プリセットのファイル:",
      idRequired: "プリセットの識別子を入力してください。",
      idInvalid: "英小文字、数字、ハイフンを使い、先頭は英小文字か数字にしてください。",
      idTaken: "この識別子のプリセットはすでに存在します。",
      deleteTitle: "このプリセットを削除しますか？",
      deleteDescription: "プリセットのディレクトリを削除します。すでに実行中のセッションはそのまま動作しますが、新しいセッションでは選択できなくなります。",
      deleteConfirm: "削除",
      deleting: "削除中…"
    },
    settings: {
      trigger: "設定",
      title: "設定",
      close: "閉じる",
      openDocument: "設定ファイルを開く",
      "openDocument.error": "設定ファイルを開けませんでした",
      "general.nav": "一般"
    },
    "settings.models": {
      nav: "モデル",
      title: "モデル",
      intro: "以下のプロバイダーのモデルを使うには、API キーを入力してください。",
      edit: "編集",
      editProvider: "{provider} を編集",
      remove: "削除",
      removeProvider: "{provider} を削除",
      deleteTitle: "{provider} を削除しますか？",
      deleteDescription: "{provider} を削除すると、その設定が失われます。使用している認証情報は別の場所で管理されており、そのまま残ります。",
      deleteDescriptionWithCredential: "{provider} を削除すると、その設定と保存済みの API キーが失われます。",
      deleteConfirm: "{provider} を削除",
      deleting: "{provider} を削除中…",
      add: "プロバイダーを追加",
      provider: "プロバイダー",
      close: "閉じる",
      cancel: "キャンセル",
      apply: "適用",
      applying: "適用中…",
      savedProvider: "{provider} を保存しました。",
      credentialConfigured: "API キー設定済み",
      credentialMissing: "API キー未設定",
      readOnly: "このデプロイでは設定ドキュメントが読み取り専用です。",
      loadFailed: "プロバイダー一覧を読み込めませんでした",
      conflict: "このカードを開いている間に、別の場所でこの設定が変更されました。いったん閉じて開き直すと、現在の値を編集できます。",
      retry: "再試行",
      keyInput: "API キー",
      keyPlaceholder: "API キーを入力",
      keyPlaceholderNative: "API キーを入力するか、空欄にして環境側の認証を使用します",
      keyStored: "設定済み — 置き換えるには新しい値を入力してください",
      keyEnvLocked: "起動時の環境から与えられています（読み取り専用）",
      customized: "カスタマイズ済みの設定",
      baseUrl: "ベース URL",
      baseUrlDefault: "プロバイダーの既定値",
      models: "モデル",
      modelsInherited: "アダプターの既定値を使用中",
      modelsCustomized: "カスタマイズ済みのモデルカタログ",
      resetModels: "既定値に戻す",
      model: "モデル",
      modelId: "モデル ID",
      modelName: "表示名",
      modelNamePlaceholder: "空欄の場合はモデル ID を使用します",
      contextWindow: "コンテキストウィンドウ",
      contextWindowPlaceholder: "プロバイダーの既定値を使用します",
      maxTokens: "最大出力トークン数",
      maxTokensPlaceholder: "プロバイダーの既定値を使用します",
      modelAdvanced: "容量",
      addModel: "モデルを追加",
      removeModel: "モデルを削除",
      modelsEmpty: "セレクターにはモデルが表示されません。一覧にない ID も直接送信できます。",
      keyBlank: "API キーを入力するか、空欄にすると保存済みのキーをそのまま使います。",
      keyBlankNew: "API キーを入力するか、このプロバイダーが別の方法で認証する場合は空欄のままにしてください。",
      keyIllegalCharacters: "この API キーは形式が正しくありません。内容を確認してください。",
      modelIdRequired: "モデル ID を入力してください。",
      modelIdDuplicate: "モデル ID は重複できません。",
      modelNameInvalid: "表示名は空にできません。",
      modelContextInvalid: "コンテキストウィンドウは正の数で入力してください（例: 131072、256K、1M）。",
      modelMaxTokensInvalid: "最大出力トークン数は正の数で入力してください（例: 8192、64K、1M）。",
      advancedHint: "その他の項目は settings.yaml にあります。該当箇所を直接編集してください。",
      modelCapacityInvalid: "容量は数値で入力してください。末尾に K または M を付けられます。",
      modelDuplicate: "同じモデル ID は 1 度しか指定できません。",
      modelContextWindow: "コンテキストウィンドウ",
      modelMaxTokens: "最大出力トークン数",
      fetchModels: "利用可能なモデルを取得",
      fetching: "プロバイダーに問い合わせ中…",
      fetchNeedsBaseUrl: "先にベース URL を入力してから取得してください。",
      fetchEmpty: "このプロバイダーはモデルを 1 つも返しませんでした。手動で追加してください。",
      fetchTitle: "追加するモデルを選択",
      fetchDescription: "このプロバイダーで利用できるモデルです。追加するものを選んでください。",
      fetchSelectAll: "すべて選択",
      fetchDeselectAll: "選択をすべて解除",
      fetchAdopt: "選択したモデルを追加",
      customAdd: "カスタムプロバイダーを追加",
      customTitle: "カスタムプロバイダー",
      customTag: "カスタム",
      customRoute: "プロバイダー ID",
      customRouteHint: "英小文字で始まる小文字の識別子です。リクエスト内でこのプロバイダーを一意に指し、認証情報の名前にもなります。",
      customRouteInvalid: "先頭は英小文字にし、以降は英小文字、数字、ハイフンを使ってください。",
      customRouteTaken: "この ID は既に別のプロバイダーが使用しています。",
      customDisplayName: "表示名",
      customApi: "API プロトコル",
      customApiUnset: "未選択",
      customNeedsBaseUrl: "カスタムプロバイダーにはベース URL が必要です。",
      customNeedsModels: "カスタムプロバイダーには少なくとも 1 つのモデルが必要です。",
      create: "プロバイダーを作成",
      creating: "作成中…",
      welcomeTitle: "社内テストのお知らせ",
      welcomeBody: "DeepSeek Harness 0.1 は、Harness 開発者向けのテスト段階にあります。改善すべき点はまだ多く、開発者コミュニティからのフィードバックをお待ちしています。DeepSeek Harness のコアプラグインと基盤 API は、今後数か月にわたって急速に進化していきます。\n\nオープンソースで、開かれた、再利用でき、組み合わせられるインフラの上で、世界中の開発者とともに知能の限界を探っていきたいと考えています。DSH のプラグインエコシステムへの参加を、どこの Harness 開発者にも歓迎します。",
      welcomeContinue: "続ける",
      welcomeError: "確認内容を保存できませんでした。もう一度お試しください。",
      onboardingTitle: "API キーを追加して始めましょう",
      onboardingDescription: "公式の DeepSeek プロバイダーを設定すると、すぐに開発を始められます。",
      onboardingLater: "後で設定する",
      onboardingSave: "保存して続ける",
      onboardingSaving: "保存中…",
      keyRequired: "続けるには API キーを入力してください。"
    },
    "settings.permission": {
      "confirm.acknowledge": "リスクを理解した上で続行します",
      "confirm.cancel": "キャンセル",
      "confirm.description": "フルアクセスでは、新しいセッションが確認の手順を減らし、機密性の高い操作、ファイルの変更、外部コマンドの実行を含む多くの操作を直接実行できるようになります。以降のタスクを信頼できる場合にのみ使用してください。",
      "confirm.enable": "フルアクセスを有効にする",
      "confirm.title": "フルアクセスを有効にしますか？",
      description: "新しいセッションの既定の権限モードを選択します",
      loading: "読み込み中",
      title: "権限",
      unavailable: "利用できません"
    },
    "settings.pluginInventory": {
      tab: "プラグイン一覧",
      loading: "プラグインを読み込み中…",
      error: "プラグインを一時的に利用できません。",
      retry: "再試行",
      search: "プラグインを検索",
      catalog: "プラグイン一覧",
      empty: "利用できるプラグインがありません。",
      emptySearch: "一致するプラグインがありません。",
      enabledTag: "有効",
      disabledTag: "無効",
      configuration: "設定",
      cordis: "Cordis の状態",
      unobserved: "未マウント",
      pending: "依存関係の待機中",
      loadingPhase: "読み込み中",
      active: "マウント済み",
      failed: "マウント失敗",
      unloading: "アンロード中"
    },
    "settings.plugins": {
      nav: "プラグイン",
      title: "プラグイン",
      intro: "このデプロイにインストールされているプラグインを設定・確認します。",
      tabs: "プラグインの表示",
      configurableTab: "プラグインの設定",
      empty: "このデプロイにはプラグインの設定項目がありません。",
      overridden: "変更済み",
      reset: "既定値に戻す",
      readOnly: "このデプロイでは設定が読み取り専用です。",
      expand: "設定を表示",
      collapse: "設定を隠す",
      save: "保存",
      saving: "保存中…",
      discard: "破棄",
      unsaved: "未保存",
      saveFailed: "デプロイがこの値を受け付けませんでした。修正できるよう入力はそのまま残しています。",
      invalidNumber: "数値を入力するか、空欄にして既定値を使用してください。",
      bashTitle: "シェル",
      bashDescription: "エージェントが実行するすべてのコマンドに適用される制限です。",
      bashTimeoutMs: "コマンドのタイムアウト（ミリ秒）",
      bashTimeoutMsHint: "1 つのコマンドが終了させられるまでに実行できる時間です。",
      bashMaxOutputBytes: "ストリームごとの出力上限（バイト）",
      bashMaxOutputBytesHint: "これを超えた出力は失われず、一時ファイルに書き出されます。",
      agentLoopTitle: "エージェントループ",
      agentLoopDescription: "エージェントがツール呼び出しをどう振り分けるかです。",
      agentLoopMaxParallel: "並列ツール呼び出し数",
      agentLoopMaxParallelHint: "1 ステップ内で同時に実行できる並列可能な呼び出しの上限です。",
      webSearchTitle: "ウェブ検索",
      webSearchDescription: "DeepSeek の検索プロバイダーです。",
      webSearchApiKey: "API キー",
      webSearchApiKeyHint: "設定ファイルの外部に保存されます。現在のキーを保持するには空欄のままにしてください。",
      webSearchApiKeySet: "キーが設定されています。",
      webSearchApiKeyUnset: "キーが設定されていません。設定するまで検索は利用できません。",
      webSearchBaseUrl: "エンドポイント",
      webSearchBaseUrlHint: "空欄にするとプロバイダーの既定値を使用します。",
      webSearchMaxUses: "リクエストあたりの最大検索回数",
      webSearchMaxUsesHint: "1 つのリクエストが回答に至るまでに検索できる回数です。"
    },
    "settings.theme": {
      "appearance.title": "外観",
      "appearance.light": "ライト",
      "appearance.dark": "ダーク",
      "appearance.system": "システム"
    },
    sidebar: {
      "session.new": "新しいセッション",
      "session.new.label": "新しいセッションを作成",
      "toggle.open": "サイドバーを開く",
      "toggle.collapse": "サイドバーを折りたたむ"
    },
    skill: {
      "row.running": "skill を読み込み中",
      "row.failed": "skill の読み込みに失敗しました",
      "row.stopped": "skill の読み込みを中止しました",
      "row.instructions": "説明",
      "menu.userOnly": "ユーザーのみ"
    },
    "slash.menu": {
      command: "コマンド",
      skill: "スキル",
      subagent: "サブエージェント",
      loading: "読み込み中…",
      "suggestions.aria": "トリガー候補"
    },
    subagent: {
      "diagnostic.corrupt": "セッション記録が破損しています",
      "diagnostic.unsupported": "サブエージェント記録のバージョンに対応していません",
      "diagnostic.unavailable": "セッション記録を一時的に取得できません",
      "duration.seconds": "{seconds}秒",
      "duration.minutes": "{minutes}分{seconds}秒",
      "duration.hours": "{hours}時間{minutes}分{seconds}秒",
      "duration.days": "{days}日",
      "duration.daysHours": "{days}日{hours}時間",
      "duration.months": "約{months}か月",
      "duration.monthsDays": "約{months}か月{days}日",
      "duration.years": "約{years}年",
      "duration.yearsMonths": "約{years}年{months}か月",
      "duration.exactDays": "{days}日{hours}時間{minutes}分{seconds}秒",
      "duration.exactTitle": "稼働時間の合計: {duration}",
      "loading.label": "サブエージェントを読み込み中…",
      "loading.aria": "サブエージェントを読み込み中",
      "load.error": "サブエージェントを読み込めません",
      retry: "再試行",
      "mode.oneShot": "単発",
      "mode.continuable": "継続可能",
      "activity.running": "実行中",
      "activity.inactive": "停止中",
      "branch.collapse": "{label} の配下を折りたたむ",
      "branch.expand": "{label} の配下を展開",
      "count.total.one": "サブエージェント {count} 件",
      "count.total.other": "サブエージェント {count} 件",
      "count.running.one": "サブエージェント {count} 件を実行中",
      "count.running.other": "サブエージェント {count} 件を実行中",
      "switcher.aria": "サブエージェントを切り替え: {title}",
      "tree.aria": "サブエージェントのセッション",
      "readonly.oneShot.title": "単発サブエージェントの記録",
      "readonly.title": "このサブエージェントは現在読み取り専用です",
      "readonly.oneShot.body": "単発タスクは追加の指示を受け付けません。ここで実行記録の全体を確認できます。",
      "readonly.body": "親セッションがオフラインです。メッセージを送信するには親セッションを開き直してください。"
    },
    trajectory: {
      "view.trajectory": "トラジェクトリ",
      "toolbar.aria": "トラジェクトリのツールバー",
      "toolbar.duration": "時間軸",
      "toolbar.useActualDuration": "実時間で表示",
      "toolbar.useEqualWidth": "操作を等幅で表示",
      "toolbar.actualTime": "実時間",
      "toolbar.turns": "ターン",
      "toolbar.expandTurns": "ターンを展開",
      "toolbar.collapseTurns": "ターンを折りたたむ",
      "toolbar.calls": "呼び出し",
      "toolbar.expandCalls": "呼び出しを展開",
      "toolbar.collapseCalls": "呼び出しを折りたたむ",
      "toolbar.search": "トラジェクトリを検索",
      "toolbar.searchPlaceholder": "検索"
    },
    workflowRun: {
      "run.title": "{name}",
      "run.members.one": "メンバー {count} 件",
      "run.members.other": "メンバー {count} 件",
      "run.empty": "開始されたメンバーはありません",
      "phase.unassigned": "フェーズなし",
      "phase.empty": "フェーズ名が空です",
      "statusCount.running": "実行中 {count}",
      "statusCount.completed": "完了 {count}",
      "statusCount.failed": "失敗 {count}",
      "statusCount.cancelled": "キャンセル {count}",
      "statusCount.interrupted": "中断 {count}",
      "member.empty": "メンバー名が空です",
      "member.open": "{name} を開く",
      "status.running": "実行中",
      "status.completed": "完了",
      "status.failed": "失敗",
      "status.cancelled": "キャンセル済み",
      "status.interrupted": "中断"
    },
    workspace: {
      "group.ungrouped": "未分類",
      "session.new": "新規セッション",
      "section.workspaces": "ワークスペース",
      "section.sessions": "セッション",
      "viewOptions.label": "表示オプション",
      "groupBy.label": "グループ化",
      "groupBy.workspace": "ワークスペース",
      "groupBy.flat": "1 つのリストにまとめる",
      "orderBy.label": "並び順",
      "orderBy.manual": "手動",
      "orderBy.updated": "最終更新",
      "sessions.expand": "他 {n} 件のセッションを表示",
      "sessions.collapse": "表示を減らす",
      "empty.none": "セッションはまだありません",
      "empty.noMatches": "一致するものがありません",
      "workspace.add": "ワークスペースを追加",
      "search.sessions.aria": "セッションを検索",
      "search.placeholder": "セッションを検索...",
      "search.clear": "検索をクリア",
      "search.results.aria": "検索結果",
      "search.pending": "セッション履歴を検索中…",
      "search.unavailable": "本文検索を一時的に利用できません。名前が一致したものを表示しています。",
      "search.noMatches": "一致するセッションがありません",
      "search.hasMore": "先頭 {n} 件の結果を表示しています。検索条件を絞り込んでください。",
      "menu.addWorkspace": "ワークスペースを追加…",
      "picker.loading": "ワークスペースを読み込み中…",
      "conflict.named": "「{name}」という名前のワークスペースはすでに存在します。",
      "folderError.title": "フォルダを開けませんでした",
      "folderError.retry": "選び直す",
      rename: "名前を変更",
      "rename.workspace.title": "ワークスペースの名前を変更",
      "rename.session.title": "セッションの名前を変更",
      "field.workspaceName": "ワークスペース名",
      "field.sessionName": "セッション名",
      "delete.workspace": "ワークスペースを削除",
      "delete.desc": "「{name}」をワークスペース一覧から取り除きます。フォルダとセッションログは残ります。このワークスペースのセッションは「未分類」に表示されます。",
      "delete.pending": "ワークスペースを削除中…",
      "menu.fork": "セッションをフォーク",
      "menu.archiveSession": "セッションをアーカイブ",
      "sessions.count.one": "{n} 件のセッション",
      "sessions.count.other": "{n} 件のセッション",
      "actions.workspace.aria": "{name} のワークスペース操作",
      "actions.session.aria": "{name} のセッション操作",
      "actions.newSession.aria": "{name} で新規セッション",
      "status.running": "実行中",
      "status.subagentsRunning.one": "サブエージェント {n} 件を実行中",
      "status.subagentsRunning.other": "サブエージェント {n} 件を実行中",
      "status.idle": "待機中",
      "status.waitingApproval": "承認待ち",
      "status.planReview": "プランの確認待ち",
      "status.waitingAnswer": "回答待ち",
      "status.completed": "完了",
      "hover.created": "作成 {time}",
      "hover.copied": "コピーしました",
      "date.ymd": "{y}/{m}/{d}",
      "time.now": "たった今",
      "time.minutes": "{n}分",
      "time.hours": "{n}時間",
      "time.days": "{n}日",
      "time.months": "{n}か月",
      "time.years": "{n}年",
      "time.ago": "{t}前"
    }
  },
  ko: {
    command: {
      "search.placeholder": "검색…",
      "search.aria": "옵션 필터링",
      "status.loading": "옵션 불러오는 중…",
      "status.applying": "적용 중…",
      "status.empty": "옵션 없음",
      "overlay.aria": "/{command} 옵션",
      "listbox.aria": "/{command} 일치 항목",
      "notice.imagesUnsupported": "/{command} 명령은 이미지 첨부를 지원하지 않습니다. 이미지를 먼저 제거하세요"
    },
    conversation: {
      "access.confirm.acknowledge": "위험을 이해했으며 계속 진행합니다",
      "access.confirm.cancel": "취소",
      "access.confirm.description": "전체 액세스를 켜면 확인 단계가 줄어들고, 에이전트가 민감한 작업이나 파일 변경, 외부 명령 실행을 포함한 더 많은 작업을 직접 수행할 수 있습니다. 현재 작업을 신뢰할 수 있을 때만 사용하세요.",
      "access.confirm.enable": "전체 액세스 사용",
      "access.confirm.title": "전체 액세스를 사용하시겠습니까?",
      "approval.allowOnce": "한 번만 허용",
      "approval.detail.aria": "승인 세부 정보",
      "approval.escalation": "도구 {toolName}이(가) 권한 상승 실행을 요청합니다",
      "approval.reject": "거부",
      "approval.waiting": "승인 대기 중",
      "ask.answered": "{answered}/{total}개 답변함",
      "ask.cancelled": "취소됨",
      "ask.interrupted": "중단됨",
      "ask.rowTitle": "질문하기",
      "ask.waiting": "대기 중",
      "bash.failed": "실패",
      "bash.running": "실행 중",
      "bash.stopped": "중지됨",
      "chat.loadError": "기록을 불러오지 못했습니다: {message} ({code})",
      "chat.loadOlder": "이전 기록 불러오기",
      "chat.loadingHistory": "기록을 불러오는 중…",
      "chat.toBottom": "맨 아래로",
      "clock.md": "{m}/{d}",
      "clock.ymd": "{y}-{m}-{d}",
      "command.done": "완료",
      "command.failed": "명령이 실패했습니다",
      "command.imagesUnsupported": "/{command}은(는) 이미지 첨부를 받지 않습니다. 먼저 삭제하세요",
      "command.running": "실행 중…",
      "command.title": "명령",
      "context.aria": "컨텍스트의 {percent} 사용",
      "context.messages": "메시지",
      "context.system": "시스템 프롬프트",
      "context.tools": "도구",
      "context.used": "의 컨텍스트 사용",
      "details.close": "세부 정보 닫기",
      "details.empty": "메시지 흐름에서 도구 행을 클릭하면 세부 정보가 표시됩니다",
      "details.input": "입력",
      "details.notInWindow": "이 호출은 현재 표시 범위 밖에 있습니다",
      "details.output": "출력",
      "details.running": "실행 중…",
      "details.title": "세부 정보",
      "duration.minutes": "{minutes}분 {seconds}초",
      "duration.seconds": "{seconds}초",
      "fileOpen.folderTitle": "폴더를 열지 못했습니다",
      "fileOpen.folderUnknown": "이 폴더는 열 수 없습니다",
      "fileOpen.title": "파일을 열지 못했습니다",
      "fileOpen.unknown": "이 파일은 열 수 없습니다",
      "hero.chooseWorkspace": "작업 공간 선택",
      "hero.headline": "Into the Unknown",
      "hero.preview": "미리보기",
      "hint.goal": "오래 걸리는 작업의 목적을 설명하세요",
      "hint.goal.active": "목표 설정됨 — 편집 / 일시 중지 / 재개 / 지우기",
      "hint.plan": "작업을 설명하면 플랜을 만듭니다",
      "image.closePreview": "원본 이미지 미리보기 닫기",
      "image.dimensionTooLarge": "이미지 한 변은 최대 {size}px입니다. 축소한 뒤 다시 시도하세요",
      "image.dropBlocked": "지금은 이미지를 추가할 수 없습니다",
      "image.dropDesc": "최대 {count}장, 장당 {size}까지",
      "image.dropTitle": "여기에 이미지를 끌어다 놓아 추가하세요",
      "image.fileTooLarge": "이미지는 장당 {size} 미만이어야 합니다",
      "image.label": "이미지",
      "image.loadFailed": "이미지를 불러오지 못했습니다. 클릭하면 다시 시도합니다",
      "image.loading": "이미지를 불러오는 중…",
      "image.modelUnsupported": "현재 모델은 이미지를 지원하지 않습니다. 지원하는 모델로 바꾸세요",
      "image.openOriginal": "원본 보기",
      "image.openOriginalLabel": "{label}, 클릭하면 원본을 봅니다",
      "image.original": "원본 이미지",
      "image.pending": "전송 대기 중인 이미지",
      "image.preview": "원본 이미지 미리보기",
      "image.remove": "이미지 {name} 삭제",
      "image.scrollLeft": "이미지 왼쪽으로 스크롤",
      "image.scrollRight": "이미지 오른쪽으로 스크롤",
      "image.sendFailed": "이미지 전송에 실패했습니다({reason}). 다시 추가한 뒤 시도하세요",
      "image.serviceUnavailable": "이미지 로딩 서비스를 사용할 수 없습니다",
      "image.subagentUnsupported": "서브에이전트 세션은 아직 이미지를 지원하지 않습니다",
      "image.tooMany": "메시지 하나에 최대 {count}장까지 넣을 수 있습니다",
      "image.tooManyPixels": "이미지 해상도가 너무 높습니다. 압축한 뒤 다시 시도하세요",
      "image.totalTooLarge": "이미지 합계가 {size}을(를) 넘었습니다. 일부를 삭제한 뒤 다시 시도하세요",
      "image.unsupportedType": "PNG, JPG, WebP, GIF 형식만 지원합니다",
      "input.accessMode": "액세스 모드, 현재: {name}",
      "input.commands": "명령",
      "input.send": "메시지 보내기",
      "input.stop": "생성 중지",
      "json.truncated": "… 잘렸습니다. 전체 {total}자",
      "message.branch": "여기에서 새 대화로 분기",
      "message.branchUnavailable": "완료된 턴의 마지막 메시지에서만 사용할 수 있습니다",
      "message.compaction": "컨텍스트를 압축했습니다",
      "message.compaction.completed": "기록 {items}개를 압축했습니다(약 {tokens} 토큰)",
      "message.compaction.expand": "압축 요약 보기",
      "message.compaction.running": "컨텍스트를 압축하는 중…",
      "message.compaction.unavailable": "압축 요약을 사용할 수 없습니다",
      "message.context.catalog.more": "… {count}개 더",
      "message.context.catalog.replaced": "대체된 카탈로그",
      "message.context.instructions.added": "추가됨",
      "message.context.instructions.loaded": "불러옴",
      "message.context.instructions.removed": "제거됨",
      "message.context.instructions.updated": "업데이트됨",
      "message.context.recall.counts": "{retained}개 유지 · {omitted}개 제외",
      "message.context.recall.truncated": "잘림",
      "message.context.relay.from": "세션 {session}에서",
      "message.context.snapshot.supersedes": "이전 스냅샷을 대체합니다",
      "message.contextInjection": "컨텍스트 주입",
      "message.contextRecall": "세션 불러오기",
      "message.extraBlock": "추가 콘텐츠 블록",
      "message.maxTokens": "출력 토큰 한도에 도달했습니다",
      "message.maxTokens.hint": '답변이 중간에 끊겼지만 그때까지의 출력은 대화에 남아 있습니다. "continue"를 보내면 모델이 이어서 진행합니다.',
      "message.ranFor": "실행 시간 {duration}",
      "message.referenceSeparator": ", ",
      "message.referenceSummary": "참조한 세션 · {labels}",
      "message.retry.active": "모델 요청을 다시 시도하는 중",
      "message.retry.cancelled": "모델 요청 재시도를 취소했습니다",
      "message.retry.delay": "재시도 대기 시간: ",
      "message.retry.failure": "실패 원인: ",
      "message.retry.scheduled": "모델 요청 재시도를 기다리는 중",
      "message.retry.started": "모델 요청을 다시 시도했습니다",
      "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}초",
      "message.stopped": "중지됨",
      "message.tokensPerSecond": "{tps} tok/s",
      "message.ttft": "TTFT {seconds}초",
      "message.turnError": "이 턴은 실패했습니다",
      "message.unknownBlock": "알 수 없는 콘텐츠 블록",
      "message.unknownSurface": "알 수 없는 표시 이벤트: {type}",
      "placeholder.default": "에이전트에게 메시지 보내기",
      "placeholder.hero": "만들고 싶은 것을 설명해 주세요",
      "placeholder.parentOffline": "상위 세션이 오프라인입니다. 전송은 할 수 없지만 실행 중지는 가능합니다",
      "placeholder.plan": "작업을 설명하면 플랜을 만듭니다",
      "placeholder.steerQueue": "Cmd/Ctrl+Enter로 대기 중인 메시지 전체에 반영합니다",
      "placeholder.unavailable": "세션을 사용할 수 없습니다",
      "placeholder.workspace": "작업 공간을 선택해 시작하세요",
      "queue.cancelEdit": "편집 취소",
      "queue.count": "대기 중인 메시지 {n}개",
      "queue.edit": "대기 중인 메시지 편집",
      "queue.edit.unsupported": "텍스트가 아닌 내용이 있어 아직 편집할 수 없습니다",
      "queue.editFailed": "편집하지 못했습니다. 이 메시지는 이미 전송이 시작되었을 수 있습니다.",
      "queue.remove": "대기 중인 메시지 삭제",
      "queue.removeFailed": "삭제하지 못했습니다. 이 메시지는 이미 전송이 시작되었을 수 있습니다.",
      "queue.save": "대기 중인 메시지 저장",
      "queue.steer": "대기 중인 메시지로 방향 바꾸기",
      "queue.steer.unavailable": "방향 바꾸기는 에이전트가 실행 중일 때만 사용할 수 있습니다",
      "queue.steerFailed": "방향 바꾸기에 실패했습니다. 다시 시도해 주세요.",
      "row.failed": "실패",
      "row.running": "실행 중",
      "row.stopped": "중지됨",
      "session.hierarchy": "세션 계층",
      "settings.enter.description": "실행 중에만 적용됩니다. Cmd/Ctrl+Enter는 다른 동작을 사용합니다",
      "settings.enter.queue": "대기열에 넣기",
      "settings.enter.steer": "방향 바꾸기",
      "settings.enter.title": "실행 중 Enter 동작",
      "stats.cacheHit": "캐시 적중 {percent}%",
      "stats.counts": "{turns}턴 · {steps}단계",
      "stats.llm": "LLM {duration}",
      "stats.tokens": "입력 {input} tok · 출력 {output} tok",
      "stats.tokensPerSecond": "{throughput} tok/s",
      "stats.toolCall": "도구 호출 {duration}",
      "stats.ttftAverage": "TTFT 평균 {duration}",
      "terminal.collapseAria": "출력 접기",
      "terminal.done": "완료",
      "terminal.exitCode": "종료 코드 {code}",
      "terminal.expandAria": "남은 출력 {n}줄 펼치기",
      "terminal.expandRest": "… {n}줄 더",
      "terminal.failed": "실패",
      "terminal.noOutput": "출력이 없습니다",
      "terminal.running": "실행 중",
      "terminal.signal": "시그널 {signal}",
      "todo.completed": "{done}/{total}개 완료",
      "todo.progress.active": "{active}개 진행 중",
      "todo.progress.done": "{done}개 완료",
      "todo.progress.pending": "{pending}개 대기",
      "todo.rowTitle": "할 일 목록 업데이트",
      "todo.title": "할 일",
      "view.chat": "채팅"
    },
    deliverables: {
      "produced.label": "산출물",
      "produced.moreOne": "+ 파일 1개",
      "produced.more": "+ 파일 {count}개",
      "produced.open": "{name} 열기",
      "produced.showInFolder": "폴더에서 보기"
    },
    "directory-browser": {
      "browser.title": "작업 공간 디렉터리 선택",
      "browser.home": "홈",
      "browser.newFolder": "새 폴더",
      "browser.folderName": "폴더 이름",
      "browser.createIn": '"{name}" 안에 새 폴더',
      "browser.untitledFolder": "제목 없는 폴더",
      "browser.create": "만들기",
      "browser.cancel": "취소",
      "browser.open": "열기",
      "browser.editPath": "경로 편집",
      "browser.loading": "불러오는 중…",
      "browser.truncated": "폴더가 너무 많아 앞부분만 표시합니다.",
      "browser.showHidden": "숨김 파일 표시"
    },
    feedback: {
      "action.like": "좋은 답변",
      "action.likeActive": "평가 취소",
      "action.dislike": "아쉬운 답변",
      "action.dislikeActive": "평가 취소",
      "note.open": "메모 추가",
      "note.dialog": "피드백",
      "note.placeholder": "어떤 점이 좋았는지, 또는 무엇이 잘못되었는지 알려주세요 (선택)",
      "note.save": "저장",
      "note.cancel": "취소",
      "note.aria": "피드백 메모",
      "error.conflict": "이 피드백이 다른 곳에서 변경되어 최신 상태를 표시합니다",
      "error.load": "피드백을 불러오지 못했습니다",
      "error.generic": "피드백을 저장하지 못했습니다"
    },
    goal: {
      "phase.active": "진행 중인 목표",
      "phase.paused": "일시 중지된 목표",
      "phase.blocked": "차단된 목표",
      "objective.aria": "목표 내용",
      "commandInput.aria": "명령 입력",
      "action.save": "목표 저장",
      "action.cancel": "편집 취소",
      "action.pause": "목표 일시 중지",
      "action.resume": "목표 재개",
      "action.edit": "목표 편집",
      "action.clear": "목표 지우기"
    },
    job: {
      "count.live.one": "백그라운드 작업 {count}개 실행 중",
      "count.live.other": "백그라운드 작업 {count}개 실행 중",
      "count.idle.one": "백그라운드 작업 {count}개",
      "count.idle.other": "백그라운드 작업 {count}개",
      "list.aria": "백그라운드 작업",
      "status.running": "실행 중",
      "status.stopping": "중지 중",
      "status.completed": "완료",
      "status.killed": "취소됨",
      "status.failed": "실패",
      "duration.seconds": "{seconds}초",
      "duration.minutes": "{minutes}분 {seconds}초",
      "duration.hours": "{hours}시간 {minutes}분",
      "duration.title.live": "{duration} 동안 실행 중",
      "duration.title.done": "소요 시간 {duration}"
    },
    model: {
      "command.description": "이 대화에 사용할 모델을 선택합니다",
      "option.loadError": "카탈로그를 불러오지 못했습니다: {message}",
      "trigger.fallback": "모델 선택",
      "trigger.selectAria": "모델 선택",
      "trigger.aria": "모델 선택, 현재 {model}",
      "trigger.ariaEffort": "모델 선택, 현재 {model}, 추론 강도 {effort}",
      "menu.aria": "모델 및 추론 강도",
      "menu.model": "모델",
      "menu.effort": "추론 강도",
      "effort.providerDefault": "기본값",
      "status.loading": "모델 목록을 새로 고치는 중…",
      "error.action": "모델 작업에 실패했습니다: {message}",
      "action.reload": "다시 불러오기",
      "warning.groupLoad": "{name}을(를) 불러오지 못했습니다: {message}",
      "empty.models": "사용할 수 있는 모델이 없습니다.",
      "blocked.composer": "이 모델은 사용할 수 없습니다. 다른 모델을 선택하세요",
      "empty.efforts": "이 모델에는 추론 강도 선택지가 없습니다."
    },
    "permission.access": {
      "confirm.acknowledge": "위험을 이해했으며 계속 진행합니다",
      "confirm.cancel": "취소",
      "confirm.description": "전체 액세스를 켜면 확인 단계가 줄어들고, 에이전트가 민감한 작업이나 파일 변경, 외부 명령 실행을 포함한 더 많은 작업을 직접 수행할 수 있습니다. 현재 작업을 신뢰할 수 있을 때만 사용하세요.",
      "confirm.enable": "전체 액세스 사용",
      "confirm.title": "전체 액세스를 사용하시겠습니까?"
    },
    plan: {
      "chip.on.aria": "plan mode 켜짐, 누르면 꺼집니다",
      "chip.on.title": "plan mode 켜짐 — 클릭하면 꺼집니다(/plan off)",
      "chip.off.aria": "plan mode 꺼짐, 누르면 켜집니다",
      "chip.off.title": "plan mode 꺼짐 — 클릭하면 켜집니다(/plan)"
    },
    question: {
      "error.incomplete": "이 질문에 먼저 답해 주세요.",
      "error.unanswered": "선택지를 고르거나 직접 답을 입력해 주세요.",
      "nav.prev": "이전 질문",
      "nav.next": "다음 질문",
      "nav.minimize": "질문 카드 접기",
      "nav.maximize": "질문 카드 펼치기",
      "nav.cancel": "모든 질문 닫기",
      "option.recommended": "추천",
      "custom.placeholder": "답변 입력",
      "action.skip": "이 질문 건너뛰기",
      "action.next": "다음",
      "plan.header": "플랜 검토",
      "plan.approve": "승인",
      "plan.decline": "거절",
      "plan.discuss": "채팅으로 이야기하기"
    },
    reference: {
      "section.files": "파일 및 폴더",
      "section.sessions": "세션 대화",
      "candidate.file": "파일",
      "candidate.folder": "폴더",
      "candidate.session": "세션",
      "candidate.noCwd": "(작업 디렉터리 없음)"
    },
    "settings.agentPreset": {
      title: "에이전트 프리셋",
      description: "지금 이후로 시작하는 세션에 적용됩니다. 실행 중인 세션은 시작할 때의 프리셋을 유지합니다.",
      loading: "프리셋을 불러오는 중…",
      error: "에이전트 프리셋을 불러오지 못했습니다.",
      userTrust: "사용자 지정",
      seatHint: "곧 시작할 세션의 에이전트 프리셋",
      headerHint: "이 세션이 실행 중인 에이전트 프리셋입니다. 시작 시점에 고정됩니다",
      nav: "에이전트 프리셋",
      sectionIntro: "프리셋은 한 세션의 에이전트가 실행하는 플러그인 구성입니다. 도구, 프롬프트, 기능이 여기에서 정해집니다. 기존 프리셋을 복제해 직접 손보거나, 크리에이터 모드에서 에이전트에게 초안을 맡길 수 있습니다.",
      builtIn: "기본 제공",
      setDefault: "기본값으로 설정",
      view: "보기",
      presetStandardName: "표준 모드",
      presetStandardDescription: "파일 편집, 셸, 파일 및 웹 검색, 스킬, 플래닝, 목표, 서브에이전트, 워크플로를 갖춘 완전한 코딩 에이전트입니다.",
      presetCodeName: "PTC 모드",
      presetCodeDescription: "표준 모드의 모든 기능에 더해, 도구를 Code Mode SDK로 노출해 모델이 여러 단계의 작업을 하나의 TypeScript 프로그램으로 묶을 수 있습니다.",
      presetMinimalName: "미니멀 모드",
      presetMinimalDescription: "지속형 bash와 str_replace_editor 두 가지 도구만 사용하는 코딩 에이전트입니다.",
      presetCordisName: "크리에이터 모드",
      presetCordisDescription: "사용자 지정 에이전트 프리셋을 만들기 위한 모드입니다. 표준 모드의 모든 기능에 더해 런타임 점검, 플러그인 실험, 프리셋 작성 안내를 제공합니다.",
      duplicate: "복제",
      duplicateUnavailable: "이 배포에는 쓰기 가능한 프리셋 디렉터리가 없습니다",
      delete: "삭제",
      presetId: "식별자",
      presetIdPlaceholder: "my-agent",
      displayName: "이름",
      displayNamePlaceholder: "선택 화면에 표시됩니다. 비워 두면 식별자를 사용합니다",
      inUse: "사용 중",
      builtInGroup: "기본 제공",
      customGroup: "사용자 지정",
      noDescription: "설명이 없습니다.",
      brokenBadge: "불러오기 실패",
      brokenNoCopy: "불러오지 못한 프리셋은 복제할 수 없습니다",
      copyOf: "복제 원본",
      composition: "구성 (agent.cordis.yml)",
      cancel: "취소",
      close: "닫기",
      retry: "다시 시도",
      copyTitle: "프리셋 복제",
      copyIntro: "프리셋 전체가 이 컴퓨터에 복제됩니다. 식별자는 그 디렉터리 이름이 되며 나중에 바꿀 수 없습니다. 나머지는 프리셋 자체 파일에서 편집합니다.",
      create: "만들기",
      creating: "만드는 중…",
      creatorDraft: "크리에이터 모드로 사용자 지정 프리셋 초안 만들기",
      openLocation: "폴더 열기",
      showLocation: "위치 표시",
      revealedPathLabel: "프리셋 파일:",
      idRequired: "프리셋 식별자를 입력하세요.",
      idInvalid: "영소문자, 숫자, 하이픈만 사용하고 첫 글자는 영소문자나 숫자여야 합니다.",
      idTaken: "이 식별자를 사용하는 프리셋이 이미 있습니다.",
      deleteTitle: "이 프리셋을 삭제할까요?",
      deleteDescription: "프리셋 디렉터리를 삭제합니다. 이미 실행 중인 세션은 계속 동작하지만, 새 세션에서는 선택할 수 없습니다.",
      deleteConfirm: "삭제",
      deleting: "삭제하는 중…"
    },
    settings: {
      trigger: "설정",
      title: "설정",
      close: "닫기",
      openDocument: "구성 파일 열기",
      "openDocument.error": "구성 파일을 열 수 없습니다",
      "general.nav": "일반"
    },
    "settings.models": {
      nav: "모델",
      title: "모델",
      intro: "다음 제공자의 모델을 사용하려면 API 키를 입력하세요.",
      edit: "편집",
      editProvider: "{provider} 편집",
      remove: "삭제",
      removeProvider: "{provider} 삭제",
      deleteTitle: "{provider}을(를) 삭제할까요?",
      deleteDescription: "{provider}을(를) 삭제하면 해당 설정이 사라집니다. 사용 중인 자격 증명은 다른 곳에서 관리되며 그대로 유지됩니다.",
      deleteDescriptionWithCredential: "{provider}을(를) 삭제하면 해당 설정과 저장된 API 키가 사라집니다.",
      deleteConfirm: "{provider} 삭제",
      deleting: "{provider}을(를) 삭제하는 중…",
      add: "제공자 추가",
      provider: "제공자",
      close: "닫기",
      cancel: "취소",
      apply: "적용",
      applying: "적용하는 중…",
      savedProvider: "{provider}을(를) 저장했습니다.",
      credentialConfigured: "API 키 설정됨",
      credentialMissing: "API 키 없음",
      readOnly: "이 배포에서는 설정 문서가 읽기 전용입니다.",
      loadFailed: "제공자 목록을 불러오지 못했습니다",
      conflict: "이 카드를 열어 둔 사이에 다른 곳에서 설정이 변경되었습니다. 닫았다가 다시 열면 현재 값을 편집할 수 있습니다.",
      retry: "다시 시도",
      keyInput: "API 키",
      keyPlaceholder: "API 키를 입력하세요",
      keyPlaceholderNative: "API 키를 입력하거나, 비워 두면 환경 인증을 사용합니다",
      keyStored: "설정됨 — 바꾸려면 새 값을 입력하세요",
      keyEnvLocked: "실행 환경에서 제공됨(읽기 전용)",
      customized: "사용자 지정 설정",
      baseUrl: "기본 URL",
      baseUrlDefault: "제공자 기본값",
      models: "모델",
      modelsInherited: "어댑터 기본값 사용 중",
      modelsCustomized: "사용자 지정 모델 카탈로그",
      resetModels: "기본값 복원",
      model: "모델",
      modelId: "모델 ID",
      modelName: "표시 이름",
      modelNamePlaceholder: "비워 두면 모델 ID를 사용합니다",
      contextWindow: "컨텍스트 윈도",
      contextWindowPlaceholder: "제공자 기본값을 사용합니다",
      maxTokens: "최대 출력 토큰",
      maxTokensPlaceholder: "제공자 기본값을 사용합니다",
      modelAdvanced: "용량",
      addModel: "모델 추가",
      removeModel: "모델 삭제",
      modelsEmpty: "선택기에 모델이 표시되지 않습니다. 목록에 없는 ID도 직접 보낼 수 있습니다.",
      keyBlank: "API 키를 입력하거나, 비워 두면 저장된 키를 그대로 사용합니다.",
      keyBlankNew: "API 키를 입력하거나, 이 제공자가 다른 방식으로 인증한다면 비워 두세요.",
      keyIllegalCharacters: "이 API 키는 형식이 올바르지 않습니다. 다시 확인해 주세요.",
      modelIdRequired: "모델 ID는 필수입니다.",
      modelIdDuplicate: "모델 ID는 중복될 수 없습니다.",
      modelNameInvalid: "표시 이름은 비워 둘 수 없습니다.",
      modelContextInvalid: "컨텍스트 윈도는 131072, 256K, 1M처럼 양수로 입력해야 합니다.",
      modelMaxTokensInvalid: "최대 출력 토큰은 8192, 64K, 1M처럼 양수로 입력해야 합니다.",
      advancedHint: "나머지 항목은 settings.yaml에 있습니다. 해당 부분을 직접 편집하세요.",
      modelCapacityInvalid: "용량은 숫자여야 하며, 뒤에 K 또는 M을 붙일 수 있습니다.",
      modelDuplicate: "같은 모델 ID는 한 번만 지정할 수 있습니다.",
      modelContextWindow: "컨텍스트 윈도",
      modelMaxTokens: "최대 출력 토큰",
      fetchModels: "사용 가능한 모델 가져오기",
      fetching: "제공자에 요청하는 중…",
      fetchNeedsBaseUrl: "먼저 기본 URL을 입력한 뒤 가져오세요.",
      fetchEmpty: "이 제공자가 모델을 하나도 반환하지 않았습니다. 직접 추가하세요.",
      fetchTitle: "추가할 모델 선택",
      fetchDescription: "이 제공자에서 사용할 수 있는 모델입니다. 추가할 항목을 선택하세요.",
      fetchSelectAll: "모두 선택",
      fetchDeselectAll: "선택 모두 해제",
      fetchAdopt: "선택한 모델 추가",
      customAdd: "사용자 지정 제공자 추가",
      customTitle: "사용자 지정 제공자",
      customTag: "사용자 지정",
      customRoute: "제공자 ID",
      customRouteHint: "영소문자로 시작하는 소문자 식별자입니다. 요청에서 이 제공자를 고유하게 가리키며 자격 증명 이름으로도 쓰입니다.",
      customRouteInvalid: "첫 글자는 영소문자여야 하고, 이후에는 영소문자, 숫자, 하이픈을 사용하세요.",
      customRouteTaken: "이 ID는 이미 다른 제공자가 사용 중입니다.",
      customDisplayName: "표시 이름",
      customApi: "API 프로토콜",
      customApiUnset: "선택 안 함",
      customNeedsBaseUrl: "사용자 지정 제공자에는 기본 URL이 필요합니다.",
      customNeedsModels: "사용자 지정 제공자에는 모델이 최소 하나 필요합니다.",
      create: "제공자 만들기",
      creating: "만드는 중…",
      welcomeTitle: "내부 테스트 안내",
      welcomeBody: "DeepSeek Harness 0.1은 Harness 개발자를 위한 테스트 단계에 있습니다. 개선할 부분이 아직 많으며, 개발자 커뮤니티의 의견을 기다립니다. DeepSeek Harness의 핵심 플러그인과 기반 API는 앞으로 몇 달 동안 빠르게 발전할 예정입니다.\n\n오픈 소스이자 개방적이고, 재사용할 수 있으며, 조합 가능한 인프라 위에서 전 세계 개발자와 함께 지능의 한계를 탐구하고자 합니다. 어디에 있든 Harness 개발자라면 누구나 DSH 플러그인 생태계에 참여해 주세요.",
      welcomeContinue: "계속",
      welcomeError: "확인 내용을 저장하지 못했습니다. 다시 시도해 주세요.",
      onboardingTitle: "API 키를 추가하고 시작하세요",
      onboardingDescription: "공식 DeepSeek 제공자를 설정하면 바로 개발을 시작할 수 있습니다.",
      onboardingLater: "나중에 설정",
      onboardingSave: "저장하고 계속",
      onboardingSaving: "저장 중…",
      keyRequired: "계속하려면 API 키를 입력하세요."
    },
    "settings.permission": {
      "confirm.acknowledge": "위험을 이해했으며 계속 진행합니다",
      "confirm.cancel": "취소",
      "confirm.description": "전체 액세스를 켜면 새 세션이 확인 단계를 줄이고, 민감한 작업이나 파일 변경, 외부 명령 실행을 포함한 더 많은 작업을 직접 수행할 수 있습니다. 이후 작업을 신뢰할 수 있을 때만 사용하세요.",
      "confirm.enable": "전체 액세스 사용",
      "confirm.title": "전체 액세스를 사용하시겠습니까?",
      description: "새 세션에 적용할 기본 권한 모드를 선택합니다",
      loading: "불러오는 중",
      title: "권한",
      unavailable: "사용할 수 없음"
    },
    "settings.pluginInventory": {
      tab: "플러그인 목록",
      loading: "플러그인을 읽는 중…",
      error: "플러그인을 일시적으로 사용할 수 없습니다.",
      retry: "다시 시도",
      search: "플러그인 검색",
      catalog: "플러그인 목록",
      empty: "사용할 수 있는 플러그인이 없습니다.",
      emptySearch: "일치하는 플러그인이 없습니다.",
      enabledTag: "사용",
      disabledTag: "사용 안 함",
      configuration: "설정",
      cordis: "Cordis 상태",
      unobserved: "마운트되지 않음",
      pending: "의존성 대기 중",
      loadingPhase: "불러오는 중",
      active: "마운트됨",
      failed: "마운트 실패",
      unloading: "언로드 중"
    },
    "settings.plugins": {
      nav: "플러그인",
      title: "플러그인",
      intro: "이 배포에 설치된 플러그인을 설정하고 확인합니다.",
      tabs: "플러그인 보기",
      configurableTab: "플러그인 설정",
      empty: "이 배포에는 플러그인 설정 항목이 없습니다.",
      overridden: "변경됨",
      reset: "기본값으로 되돌리기",
      readOnly: "이 배포에서는 설정이 읽기 전용입니다.",
      expand: "설정 표시",
      collapse: "설정 숨기기",
      save: "저장",
      saving: "저장 중…",
      discard: "취소",
      unsaved: "저장되지 않음",
      saveFailed: "배포가 이 값을 받아들이지 않았습니다. 수정할 수 있도록 입력은 그대로 두었습니다.",
      invalidNumber: "숫자를 입력하거나, 비워 두면 기본값을 사용합니다.",
      bashTitle: "셸",
      bashDescription: "에이전트가 실행하는 모든 명령에 적용되는 제한입니다.",
      bashTimeoutMs: "명령 제한 시간(ms)",
      bashTimeoutMsHint: "명령 하나가 종료되기 전까지 실행될 수 있는 시간입니다.",
      bashMaxOutputBytes: "스트림별 출력 상한(바이트)",
      bashMaxOutputBytesHint: "이를 넘는 출력은 사라지지 않고 임시 파일에 기록됩니다.",
      agentLoopTitle: "에이전트 루프",
      agentLoopDescription: "에이전트가 도구 호출을 어떻게 배분하는지 결정합니다.",
      agentLoopMaxParallel: "병렬 도구 호출 수",
      agentLoopMaxParallelHint: "한 단계 안에서 동시에 실행할 수 있는 병렬 가능 호출의 상한입니다.",
      webSearchTitle: "웹 검색",
      webSearchDescription: "DeepSeek 검색 제공자입니다.",
      webSearchApiKey: "API 키",
      webSearchApiKeyHint: "설정 파일 바깥에 저장됩니다. 현재 키를 유지하려면 비워 두세요.",
      webSearchApiKeySet: "키가 설정되어 있습니다.",
      webSearchApiKeyUnset: "키가 설정되어 있지 않습니다. 설정하기 전까지 검색을 사용할 수 없습니다.",
      webSearchBaseUrl: "엔드포인트",
      webSearchBaseUrlHint: "비워 두면 제공자 기본값을 사용합니다.",
      webSearchMaxUses: "요청당 최대 검색 횟수",
      webSearchMaxUsesHint: "한 요청이 답변에 이르기까지 검색할 수 있는 횟수입니다."
    },
    "settings.theme": {
      "appearance.title": "모양",
      "appearance.light": "라이트",
      "appearance.dark": "다크",
      "appearance.system": "시스템"
    },
    sidebar: {
      "session.new": "새 세션",
      "session.new.label": "새 세션 만들기",
      "toggle.open": "사이드바 열기",
      "toggle.collapse": "사이드바 접기"
    },
    skill: {
      "row.running": "skill 불러오는 중",
      "row.failed": "skill 불러오기 실패",
      "row.stopped": "skill 불러오기 중단됨",
      "row.instructions": "설명",
      "menu.userOnly": "사용자 전용"
    },
    "slash.menu": {
      command: "명령",
      skill: "스킬",
      subagent: "서브에이전트",
      loading: "불러오는 중…",
      "suggestions.aria": "트리거 추천"
    },
    subagent: {
      "diagnostic.corrupt": "세션 기록이 손상되었습니다",
      "diagnostic.unsupported": "지원하지 않는 서브에이전트 기록 버전입니다",
      "diagnostic.unavailable": "세션 기록을 일시적으로 가져올 수 없습니다",
      "duration.seconds": "{seconds}초",
      "duration.minutes": "{minutes}분 {seconds}초",
      "duration.hours": "{hours}시간 {minutes}분 {seconds}초",
      "duration.days": "{days}일",
      "duration.daysHours": "{days}일 {hours}시간",
      "duration.months": "약 {months}개월",
      "duration.monthsDays": "약 {months}개월 {days}일",
      "duration.years": "약 {years}년",
      "duration.yearsMonths": "약 {years}년 {months}개월",
      "duration.exactDays": "{days}일 {hours}시간 {minutes}분 {seconds}초",
      "duration.exactTitle": "총 실행 시간: {duration}",
      "loading.label": "서브에이전트를 불러오는 중…",
      "loading.aria": "서브에이전트를 불러오는 중",
      "load.error": "서브에이전트를 불러올 수 없습니다",
      retry: "다시 시도",
      "mode.oneShot": "일회성",
      "mode.continuable": "계속 가능",
      "activity.running": "실행 중",
      "activity.inactive": "실행 중이 아님",
      "branch.collapse": "{label} 하위 항목 접기",
      "branch.expand": "{label} 하위 항목 펼치기",
      "count.total.one": "서브에이전트 {count}개",
      "count.total.other": "서브에이전트 {count}개",
      "count.running.one": "서브에이전트 {count}개 실행 중",
      "count.running.other": "서브에이전트 {count}개 실행 중",
      "switcher.aria": "서브에이전트 전환: {title}",
      "tree.aria": "서브에이전트 세션",
      "readonly.oneShot.title": "일회성 서브에이전트 기록",
      "readonly.title": "이 서브에이전트는 현재 읽기 전용입니다",
      "readonly.oneShot.body": "일회성 작업은 후속 지시를 받지 않습니다. 여기에서 전체 실행 기록을 확인할 수 있습니다.",
      "readonly.body": "상위 세션이 오프라인입니다. 메시지를 보내려면 상위 세션을 다시 여세요."
    },
    trajectory: {
      "view.trajectory": "트라젝터리",
      "toolbar.aria": "트라젝터리 도구 모음",
      "toolbar.duration": "시간축",
      "toolbar.useActualDuration": "실제 시간으로 표시",
      "toolbar.useEqualWidth": "작업을 같은 너비로 표시",
      "toolbar.actualTime": "실제 시간",
      "toolbar.turns": "턴",
      "toolbar.expandTurns": "턴 펼치기",
      "toolbar.collapseTurns": "턴 접기",
      "toolbar.calls": "호출",
      "toolbar.expandCalls": "호출 펼치기",
      "toolbar.collapseCalls": "호출 접기",
      "toolbar.search": "트라젝터리 검색",
      "toolbar.searchPlaceholder": "검색"
    },
    workflowRun: {
      "run.title": "{name}",
      "run.members.one": "멤버 {count}개",
      "run.members.other": "멤버 {count}개",
      "run.empty": "시작된 멤버가 없습니다",
      "phase.unassigned": "단계 없음",
      "phase.empty": "단계 이름이 비어 있습니다",
      "statusCount.running": "실행 중 {count}",
      "statusCount.completed": "완료 {count}",
      "statusCount.failed": "실패 {count}",
      "statusCount.cancelled": "취소 {count}",
      "statusCount.interrupted": "중단 {count}",
      "member.empty": "멤버 이름이 비어 있습니다",
      "member.open": "{name} 열기",
      "status.running": "실행 중",
      "status.completed": "완료",
      "status.failed": "실패",
      "status.cancelled": "취소됨",
      "status.interrupted": "중단됨"
    },
    workspace: {
      "group.ungrouped": "미분류",
      "session.new": "새 세션",
      "section.workspaces": "작업 공간",
      "section.sessions": "세션",
      "viewOptions.label": "보기 옵션",
      "groupBy.label": "그룹 기준",
      "groupBy.workspace": "작업 공간",
      "groupBy.flat": "한 목록으로 보기",
      "orderBy.label": "정렬 기준",
      "orderBy.manual": "수동",
      "orderBy.updated": "최근 업데이트",
      "sessions.expand": "세션 {n}개 더 보기",
      "sessions.collapse": "간단히 보기",
      "empty.none": "아직 세션이 없습니다",
      "empty.noMatches": "일치하는 항목이 없습니다",
      "workspace.add": "작업 공간 추가",
      "search.sessions.aria": "세션 검색",
      "search.placeholder": "세션 검색...",
      "search.clear": "검색 지우기",
      "search.results.aria": "검색 결과",
      "search.pending": "세션 기록을 검색하는 중…",
      "search.unavailable": "본문 검색을 일시적으로 사용할 수 없습니다. 이름이 일치하는 항목만 표시합니다.",
      "search.noMatches": "일치하는 세션이 없습니다",
      "search.hasMore": "처음 {n}개 결과만 표시합니다. 검색 범위를 좁혀 주세요.",
      "menu.addWorkspace": "작업 공간 추가…",
      "picker.loading": "작업 공간을 불러오는 중…",
      "conflict.named": "“{name}” 이름의 작업 공간이 이미 있습니다.",
      "folderError.title": "폴더를 열지 못했습니다",
      "folderError.retry": "다시 선택",
      rename: "이름 바꾸기",
      "rename.workspace.title": "작업 공간 이름 바꾸기",
      "rename.session.title": "세션 이름 바꾸기",
      "field.workspaceName": "작업 공간 이름",
      "field.sessionName": "세션 이름",
      "delete.workspace": "작업 공간 삭제",
      "delete.desc": "“{name}”을(를) 작업 공간 목록에서 제거합니다. 폴더와 세션 로그는 유지되며, 해당 세션은 미분류에 표시됩니다.",
      "delete.pending": "작업 공간을 삭제하는 중…",
      "menu.fork": "세션 포크",
      "menu.archiveSession": "세션 보관",
      "sessions.count.one": "세션 {n}개",
      "sessions.count.other": "세션 {n}개",
      "actions.workspace.aria": "{name} 작업 공간 동작",
      "actions.session.aria": "{name} 세션 동작",
      "actions.newSession.aria": "{name}에서 새 세션",
      "status.running": "실행 중",
      "status.subagentsRunning.one": "서브에이전트 {n}개 실행 중",
      "status.subagentsRunning.other": "서브에이전트 {n}개 실행 중",
      "status.idle": "대기 중",
      "status.waitingApproval": "승인 대기 중",
      "status.planReview": "플랜 검토 대기 중",
      "status.waitingAnswer": "답변 대기 중",
      "status.completed": "완료",
      "hover.created": "{time} 생성",
      "hover.copied": "복사됨",
      "date.ymd": "{y}-{m}-{d}",
      "time.now": "방금",
      "time.minutes": "{n}분",
      "time.hours": "{n}시간",
      "time.days": "{n}일",
      "time.months": "{n}개월",
      "time.years": "{n}년",
      "time.ago": "{t} 전"
    }
  }
};

// src/client/dictionaries.ts
var BACKFILL = backfill_generated_default;

// src/client/style-tag.ts
function injectStyleTag(marker, css) {
  if (typeof document === "undefined") return () => {
  };
  if (document.querySelector(`style[data-plugin="${marker}"]`) !== null) return () => {
  };
  const tag = document.createElement("style");
  tag.dataset.plugin = marker;
  tag.textContent = css;
  document.head.appendChild(tag);
  return () => {
    tag.remove();
  };
}

// src/client/fonts.ts
var TAG = "negen-locale-fonts";
var FONT_CSS = `:root:root {
  --dsw-font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Helvetica, Arial, sans-serif;
  --ds-font-family-code: 'SF Mono', 'JetBrains Mono', 'Fira Code', Consolas, 'Liberation Mono', Menlo, Courier;
}`;
function installFontFallback() {
  return injectStyleTag(TAG, FONT_CSS);
}

// src/client/styles.ts
var PREFIX = "negen-locale";
var styles = {
  row: `${PREFIX}-row`,
  rowText: `${PREFIX}-row-text`,
  title: `${PREFIX}-title`,
  selector: `${PREFIX}-selector`,
  chevron: `${PREFIX}-chevron`
};
var CSS = `
.${styles.row} {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 16px 0;
  border-bottom: 1px solid var(--dsw-alias-border-l2);
}
.${styles.rowText} {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding-right: 48px;
}
.${styles.title} {
  font-size: 14px;
  font-weight: 400;
  line-height: 22px;
  color: var(--dsw-alias-label-primary);
}
.${styles.selector} {
  display: inline-flex;
  align-items: center;
  gap: 12px;
  height: 36px;
  padding: 0 14px;
  border: none;
  border-radius: 18px;
  background: var(--dsw-alias-bg-module-platform);
  font: inherit;
  font-size: 14px;
  line-height: 22px;
  color: var(--dsw-alias-label-primary);
  cursor: pointer;
}
.${styles.selector}:hover {
  background: var(--dsw-alias-interactive-bg-hover);
}
.${styles.chevron} {
  flex: none;
}
`;
function installStyles() {
  return injectStyleTag(PREFIX, CSS);
}

// src/client/LanguageRow.tsx
var import_react = require("react");
var import_dsh_client_ui_primitives = require("@deepseek-ai/dsh-client-ui-primitives");
var import_jsx_runtime = require("react/jsx-runtime");
function LanguageRow({ t, setLocale, useStore }) {
  const active = useStore((s) => s.active);
  const options = useStore((s) => s.options);
  const [open, setOpen] = (0, import_react.useState)(false);
  const activeLabel = options.find((o) => o.id === active)?.label ?? active;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: styles.row, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: styles.rowText, children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: styles.title, children: t("language.title") }) }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      import_dsh_client_ui_primitives.Menu,
      {
        open,
        onClose: () => {
          setOpen(false);
        },
        items: options.map((o) => ({ id: o.id, label: o.label })),
        selectedId: active,
        onSelect: (id) => {
          setLocale(id);
          setOpen(false);
        },
        align: "end",
        portal: true,
        anchor: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
          "button",
          {
            type: "button",
            className: styles.selector,
            "aria-haspopup": "menu",
            "aria-expanded": open,
            onClick: () => {
              setOpen((v) => !v);
            },
            children: [
              activeLabel,
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)(import_dsh_client_ui_primitives.IconChevronDownOutline14, { className: styles.chevron })
            ]
          }
        )
      }
    )
  ] });
}

// src/client/settings-store.ts
var import_client = require("@deepseek-ai/dsh-client-runtime/client");
function createLanguageRowStore() {
  return (0, import_client.defineStore)({
    init: () => ({ active: "", options: [], revision: -1 }),
    actions: {
      sync: (d, active, options, revision) => {
        if (revision <= d.revision) return;
        d.active = active;
        d.options = options;
        d.revision = revision;
      }
    }
  });
}

// src/client/index.ts
var SETTINGS_NS = "settings.locale";
function syncDocumentLanguage(active) {
  if (typeof document === "undefined") return;
  document.documentElement.lang = DOCUMENT_LANGUAGE[active];
}
var inject = ["slots", "connection", "remote", "settingsScope"];
var name = "negen-locale";
function apply(ctx) {
  const host = ctx.settingsScope.bind({ namespace: LOCALE_SETTINGS_NAMESPACE });
  const locale = new LocaleRuntime(ctx, host);
  locale.register(COMMON_NS, { zh, "zh-TW": zhTW, ja, ko, en });
  locale.register(SETTINGS_NS, {
    "zh": zh2,
    "zh-TW": zhTW2,
    "ja": ja2,
    "ko": ko2,
    "en": en2
  });
  for (const [localeId, namespaces] of Object.entries(BACKFILL)) {
    for (const [ns, entries] of Object.entries(namespaces)) {
      ctx.effect(
        () => locale.register(ns, localeId, entries),
        `negen-locale: ${localeId}/${ns}`
      );
    }
  }
  ctx.provide("locale", locale);
  ctx.slots.installLocale(locale);
  const store = createLanguageRowStore();
  let bound;
  const sync = (snapshot) => {
    syncDocumentLanguage(snapshot.active);
    bound?.sync(
      snapshot.active,
      snapshot.locales.map((l) => ({ id: l.id, label: l.label })),
      snapshot.revision
    );
  };
  ctx.on("locale/change", sync);
  syncDocumentLanguage(locale.getLocale().active);
  ctx.effect(() => installFontFallback(), "negen-locale: font fallback");
  ctx.effect(() => installStyles(), "negen-locale: language row styles");
  const injected = (actions) => {
    bound = actions;
    sync(locale.getLocale());
    return {
      setLocale: (id) => {
        locale.setLocale(id);
      }
    };
  };
  ctx.slots.inject("settings.general.item", () => ctx.slots.register({
    name: "settings.general.item",
    id: "language",
    order: 0,
    store,
    locale: SETTINGS_NS,
    inject: injected
  }, LanguageRow));
}
return module.exports; } });
//# sourceMappingURL=client.js.map
